// ========================================
// CAF - CONFÉDÉRATION AFRICAINE DE FOOTBALL
// 54 ASSOCIATIONS MEMBRES AVEC LOGOS OFFICIELS
// Source : https://www.cafonline.com/fr/a-propos-de-la-caf/associations-membres/
// Logos provenant de sources officielles
// Dernière mise à jour : Décembre 2024
// ========================================

const cafMembersWithLogos = [
    {
        name: 'Afrique du Sud',
        nameFR: 'Afrique du Sud',
        nameEN: 'South Africa',
        code: 'RSA',
        flag: '🇿🇦',
        logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/e/ef/South_African_Football_Association_logo.svg/200px-South_African_Football_Association_logo.svg.png',
        federation: 'SAFA - South African Football Association',
        site: 'www.safa.net',
        email: 'info@safa.net',
        president: 'Danny Jordaan',
        founded: 1991,
        fifaMember: 1992,
        confederation: 'CAF',
        colors: ['#007A33', '#FFB81C', '#000000'],
        path: 'app-universal-simple.html?club=Afrique+du+Sud&logo=🇿🇦&sport=Football+Federation&league=CAF',
        region: 'Afrique Australe'
    },
    {
        name: 'Algérie',
        nameFR: 'Algérie',
        nameEN: 'Algeria',
        code: 'ALG',
        flag: '🇩🇿',
        logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Algerian_Football_Federation_logo.svg/200px-Algerian_Football_Federation_logo.svg.png',
        federation: 'FAF - Fédération Algérienne de Football',
        site: 'www.faf.dz',
        email: 'contact@faf.dz',
        president: 'Walid Sadi',
        founded: 1962,
        fifaMember: 1963,
        confederation: 'CAF',
        colors: ['#006233', '#FFFFFF', '#D21034'],
        path: 'app-universal-simple.html?club=Algérie&logo=🇩🇿&sport=Football+Federation&league=CAF',
        region: 'Afrique du Nord'
    },
    {
        name: 'Angola',
        nameFR: 'Angola',
        nameEN: 'Angola',
        code: 'ANG',
        flag: '🇦🇴',
        logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/f/fb/Angolan_Football_Federation_logo.svg/200px-Angolan_Football_Federation_logo.svg.png',
        federation: 'FAF - Federação Angolana de Futebol',
        site: 'www.faf.ao',
        email: 'faf@faf.ao',
        president: 'Artur de Almeida e Silva',
        founded: 1979,
        fifaMember: 1980,
        confederation: 'CAF',
        colors: ['#CE1126', '#FFCD00', '#000000'],
        path: 'app-universal-simple.html?club=Angola&logo=🇦🇴&sport=Football+Federation&league=CAF',
        region: 'Afrique Centrale'
    },
    {
        name: 'Bénin',
        nameFR: 'Bénin',
        nameEN: 'Benin',
        code: 'BEN',
        flag: '🇧🇯',
        logo: 'https://upload.wikimedia.org/wikipedia/fr/thumb/5/53/Logo_F%C3%A9d%C3%A9ration_b%C3%A9ninoise_de_football_2014.svg/200px-Logo_F%C3%A9d%C3%A9ration_b%C3%A9ninoise_de_football_2014.svg.png',
        federation: 'FBF - Fédération Béninoise de Football',
        site: 'www.fbf-benin.com',
        email: 'fbf@fbf-benin.com',
        president: 'Mathurin De Chacus',
        founded: 1962,
        fifaMember: 1962,
        confederation: 'CAF',
        colors: ['#008751', '#FCD116', '#E8112D'],
        path: 'app-universal-simple.html?club=Bénin&logo=🇧🇯&sport=Football+Federation&league=CAF',
        region: 'Afrique de l\'Ouest'
    },
    {
        name: 'Botswana',
        nameFR: 'Botswana',
        nameEN: 'Botswana',
        code: 'BOT',
        flag: '🇧🇼',
        logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/c/c8/Botswana_Football_Association_logo.svg/200px-Botswana_Football_Association_logo.svg.png',
        federation: 'BFA - Botswana Football Association',
        site: 'www.bfa.co.bw',
        email: 'bfa@bfa.co.bw',
        president: 'Maclean Letshwiti',
        founded: 1970,
        fifaMember: 1976,
        confederation: 'CAF',
        colors: ['#75AADB', '#000000', '#FFFFFF'],
        path: 'app-universal-simple.html?club=Botswana&logo=🇧🇼&sport=Football+Federation&league=CAF',
        region: 'Afrique Australe'
    },
    {
        name: 'Burkina Faso',
        nameFR: 'Burkina Faso',
        nameEN: 'Burkina Faso',
        code: 'BFA',
        flag: '🇧🇫',
        logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Burkina_Faso_FF.png/200px-Burkina_Faso_FF.png',
        federation: 'FBF - Fédération Burkinabè de Football',
        site: 'www.fbf.bf',
        email: 'fbf@fbf.bf',
        president: 'Lazare Banssé',
        founded: 1960,
        fifaMember: 1964,
        confederation: 'CAF',
        colors: ['#EF2B2D', '#009E49'],
        path: 'app-universal-simple.html?club=Burkina+Faso&logo=🇧🇫&sport=Football+Federation&league=CAF',
        region: 'Afrique de l\'Ouest'
    },
    {
        name: 'Burundi',
        nameFR: 'Burundi',
        nameEN: 'Burundi',
        code: 'BDI',
        flag: '🇧🇮',
        logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/6/67/Burundi_Football_Federation_logo.png/200px-Burundi_Football_Federation_logo.png',
        federation: 'FFB - Fédération de Football du Burundi',
        site: 'www.ffb.bi',
        email: 'ffb@ffb.bi',
        president: 'Révérien Ndikuriyo',
        founded: 1948,
        fifaMember: 1972,
        confederation: 'CAF',
        colors: ['#CE1126', '#1EB53A', '#FFFFFF'],
        path: 'app-universal-simple.html?club=Burundi&logo=🇧🇮&sport=Football+Federation&league=CAF',
        region: 'Afrique de l\'Est'
    },
    {
        name: 'Cameroun',
        nameFR: 'Cameroun',
        nameEN: 'Cameroon',
        code: 'CMR',
        flag: '🇨🇲',
        logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/2/27/Cameroon_Football_Federation_logo.svg/200px-Cameroon_Football_Federation_logo.svg.png',
        federation: 'FECAFOOT - Fédération Camerounaise de Football',
        site: 'www.fecafoot.cm',
        email: 'contact@fecafoot.cm',
        president: 'Samuel Eto\'o',
        founded: 1959,
        fifaMember: 1962,
        confederation: 'CAF',
        colors: ['#007A5E', '#CE1126', '#FCD116'],
        path: 'app-universal-simple.html?club=Cameroun&logo=🇨🇲&sport=Football+Federation&league=CAF',
        region: 'Afrique Centrale'
    },
    {
        name: 'Cap-Vert',
        nameFR: 'Cap-Vert',
        nameEN: 'Cape Verde',
        code: 'CPV',
        flag: '🇨🇻',
        logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/e/e1/Cape_Verde_Football_Federation_logo.svg/200px-Cape_Verde_Football_Federation_logo.svg.png',
        federation: 'FCF - Federação Caboverdiana de Futebol',
        site: 'www.fcf.cv',
        email: 'fcf@fcf.cv',
        president: 'Mário Semedo',
        founded: 1982,
        fifaMember: 1986,
        confederation: 'CAF',
        colors: ['#003893', '#CF2027', '#FFFFFF'],
        path: 'app-universal-simple.html?club=Cap-Vert&logo=🇨🇻&sport=Football+Federation&league=CAF',
        region: 'Afrique de l\'Ouest'
    },
    {
        name: 'Comores',
        nameFR: 'Comores',
        nameEN: 'Comoros',
        code: 'COM',
        flag: '🇰🇲',
        logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/7/7b/Comoros_Football_Federation_logo.png/200px-Comoros_Football_Federation_logo.png',
        federation: 'FFC - Fédération Comorienne de Football',
        site: 'www.ffc-comores.com',
        email: 'ffc@ffc-comores.com',
        president: 'Said Ali Said Athouman',
        founded: 1979,
        fifaMember: 2005,
        confederation: 'CAF',
        colors: ['#3A75C4', '#FFC61E', '#D21034', '#3D8E33'],
        path: 'app-universal-simple.html?club=Comores&logo=🇰🇲&sport=Football+Federation&league=CAF',
        region: 'Afrique de l\'Est'
    },
    {
        name: 'Congo',
        nameFR: 'Congo',
        nameEN: 'Congo',
        code: 'CGO',
        flag: '🇨🇬',
        logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/5/5a/Congo_Football_Federation_logo.png/200px-Congo_Football_Federation_logo.png',
        federation: 'FECOFOOT - Fédération Congolaise de Football',
        site: 'www.fecofoot.com',
        email: 'fecofoot@fecofoot.com',
        president: 'Jean Guy Blaise Mayolas',
        founded: 1962,
        fifaMember: 1962,
        confederation: 'CAF',
        colors: ['#009543', '#FBDE4A', '#DC241F'],
        path: 'app-universal-simple.html?club=Congo&logo=🇨🇬&sport=Football+Federation&league=CAF',
        region: 'Afrique Centrale'
    },
    {
        name: 'RD Congo',
        nameFR: 'République Démocratique du Congo',
        nameEN: 'DR Congo',
        code: 'COD',
        flag: '🇨🇩',
        logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/0/0c/DR_Congo_Football_Association_logo.svg/200px-DR_Congo_Football_Association_logo.svg.png',
        federation: 'FECOFA - Fédération Congolaise de Football-Association',
        site: 'www.fecofa.cd',
        email: 'fecofa@fecofa.cd',
        president: 'Constant Omari',
        founded: 1919,
        fifaMember: 1964,
        confederation: 'CAF',
        colors: ['#007FFF', '#F7D618', '#CE1021'],
        path: 'app-universal-simple.html?club=RD+Congo&logo=🇨🇩&sport=Football+Federation&league=CAF',
        region: 'Afrique Centrale'
    },
    {
        name: 'Côte d\'Ivoire',
        nameFR: 'Côte d\'Ivoire',
        nameEN: 'Ivory Coast',
        code: 'CIV',
        flag: '🇨🇮',
        logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/9/9f/Ivorian_Football_Federation_logo.svg/200px-Ivorian_Football_Federation_logo.svg.png',
        federation: 'FIF - Fédération Ivoirienne de Football',
        site: 'www.fif.ci',
        email: 'fif@fif.ci',
        president: 'Yacine Idriss Diallo',
        founded: 1960,
        fifaMember: 1960,
        confederation: 'CAF',
        colors: ['#F77F00', '#009E60', '#FFFFFF'],
        path: 'app-universal-simple.html?club=Côte+d%27Ivoire&logo=🇨🇮&sport=Football+Federation&league=CAF',
        region: 'Afrique de l\'Ouest'
    },
    {
        name: 'Djibouti',
        nameFR: 'Djibouti',
        nameEN: 'Djibouti',
        code: 'DJI',
        flag: '🇩🇯',
        logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/4/4d/Djibouti_Football_Federation_logo.png/200px-Djibouti_Football_Federation_logo.png',
        federation: 'FDF - Fédération Djiboutienne de Football',
        site: 'www.ffd.dj',
        email: 'ffd@ffd.dj',
        president: 'Souleiman Hassan Waberi',
        founded: 1979,
        fifaMember: 1994,
        confederation: 'CAF',
        colors: ['#6AB2E7', '#12AD2B', '#CE1126', '#FFFFFF'],
        path: 'app-universal-simple.html?club=Djibouti&logo=🇩🇯&sport=Football+Federation&league=CAF',
        region: 'Afrique de l\'Est'
    },
    {
        name: 'Égypte',
        nameFR: 'Égypte',
        nameEN: 'Egypt',
        code: 'EGY',
        flag: '🇪🇬',
        logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/2/2d/Egyptian_Football_Association_logo.svg/200px-Egyptian_Football_Association_logo.svg.png',
        federation: 'EFA - Egyptian Football Association',
        site: 'www.efa.com.eg',
        email: 'efa@efa.com.eg',
        president: 'Ahmed Megahed',
        founded: 1921,
        fifaMember: 1923,
        confederation: 'CAF',
        colors: ['#CE1126', '#FFFFFF', '#000000'],
        path: 'app-universal-simple.html?club=Égypte&logo=🇪🇬&sport=Football+Federation&league=CAF',
        region: 'Afrique du Nord'
    },
    {
        name: 'Érythrée',
        nameFR: 'Érythrée',
        nameEN: 'Eritrea',
        code: 'ERI',
        flag: '🇪🇷',
        logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/Eritrea.png/200px-Eritrea.png',
        federation: 'NFPE - National Football Federation of Eritrea',
        site: 'www.efifa.org',
        email: 'efifa@efifa.org',
        president: 'Teame Kifle',
        founded: 1996,
        fifaMember: 1998,
        confederation: 'CAF',
        colors: ['#12AD2B', '#4189DD', '#EA0437'],
        path: 'app-universal-simple.html?club=Érythrée&logo=🇪🇷&sport=Football+Federation&league=CAF',
        region: 'Afrique de l\'Est'
    },
    {
        name: 'Eswatini',
        nameFR: 'Eswatini',
        nameEN: 'Eswatini',
        code: 'SWZ',
        flag: '🇸🇿',
        logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/7/72/Eswatini_Football_Association_logo.png/200px-Eswatini_Football_Association_logo.png',
        federation: 'EFA - Eswatini Football Association',
        site: 'www.sff.org.sz',
        email: 'sff@sff.org.sz',
        president: 'Peter Simelane',
        founded: 1968,
        fifaMember: 1978,
        confederation: 'CAF',
        colors: ['#3E5EB9', '#FDD100', '#B10C0C'],
        path: 'app-universal-simple.html?club=Eswatini&logo=🇸🇿&sport=Football+Federation&league=CAF',
        region: 'Afrique Australe'
    },
    {
        name: 'Éthiopie',
        nameFR: 'Éthiopie',
        nameEN: 'Ethiopia',
        code: 'ETH',
        flag: '🇪🇹',
        logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/5/5a/Ethiopian_Football_Federation_logo.svg/200px-Ethiopian_Football_Federation_logo.svg.png',
        federation: 'EFF - Ethiopian Football Federation',
        site: 'www.efa.et',
        email: 'efa@efa.et',
        president: 'Isayas Jira',
        founded: 1943,
        fifaMember: 1953,
        confederation: 'CAF',
        colors: ['#078930', '#FCDD09', '#DA121A'],
        path: 'app-universal-simple.html?club=Éthiopie&logo=🇪🇹&sport=Football+Federation&league=CAF',
        region: 'Afrique de l\'Est'
    },
    {
        name: 'Gabon',
        nameFR: 'Gabon',
        nameEN: 'Gabon',
        code: 'GAB',
        flag: '🇬🇦',
        logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/e/ee/Gabonese_Football_Federation_logo.svg/200px-Gabonese_Football_Federation_logo.svg.png',
        federation: 'FEGAFOOT - Fédération Gabonaise de Football',
        site: 'www.fegafoot.com',
        email: 'fegafoot@fegafoot.com',
        president: 'Pierre-Alain Mounguengui',
        founded: 1962,
        fifaMember: 1963,
        confederation: 'CAF',
        colors: ['#009E60', '#FCD116', '#3A75C4'],
        path: 'app-universal-simple.html?club=Gabon&logo=🇬🇦&sport=Football+Federation&league=CAF',
        region: 'Afrique Centrale'
    },
    {
        name: 'Gambie',
        nameFR: 'Gambie',
        nameEN: 'Gambia',
        code: 'GMB',
        flag: '🇬🇲',
        logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/2/2e/Gambia_Football_Federation_logo.png/200px-Gambia_Football_Federation_logo.png',
        federation: 'GFF - Gambia Football Federation',
        site: 'www.gff.gm',
        email: 'gff@gff.gm',
        president: 'Lamin Kaba Bajo',
        founded: 1952,
        fifaMember: 1968,
        confederation: 'CAF',
        colors: ['#CE1126', '#0C1C8C', '#3A7728'],
        path: 'app-universal-simple.html?club=Gambie&logo=🇬🇲&sport=Football+Federation&league=CAF',
        region: 'Afrique de l\'Ouest'
    },
    {
        name: 'Ghana',
        nameFR: 'Ghana',
        nameEN: 'Ghana',
        code: 'GHA',
        flag: '🇬🇭',
        logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/3/30/Ghana_Football_Association_logo.svg/200px-Ghana_Football_Association_logo.svg.png',
        federation: 'GFA - Ghana Football Association',
        site: 'www.ghanafa.org',
        email: 'gfa@ghanafa.org',
        president: 'Kurt Okraku',
        founded: 1957,
        fifaMember: 1958,
        confederation: 'CAF',
        colors: ['#006B3F', '#FCD116', '#CE1126'],
        path: 'app-universal-simple.html?club=Ghana&logo=🇬🇭&sport=Football+Federation&league=CAF',
        region: 'Afrique de l\'Ouest'
    },
    {
        name: 'Guinée',
        nameFR: 'Guinée',
        nameEN: 'Guinea',
        code: 'GUI',
        flag: '🇬🇳',
        logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/Guinea_FF_%28logo%29.png/200px-Guinea_FF_%28logo%29.png',
        federation: 'FEGUIFOOT - Fédération Guinéenne de Football',
        site: 'www.feguifoot.com',
        email: 'feguifoot@feguifoot.com',
        president: 'Mamadou Antonio Souaré',
        founded: 1959,
        fifaMember: 1962,
        confederation: 'CAF',
        colors: ['#CE1126', '#FCD116', '#009460'],
        path: 'app-universal-simple.html?club=Guinée&logo=🇬🇳&sport=Football+Federation&league=CAF',
        region: 'Afrique de l\'Ouest'
    },
    {
        name: 'Guinée-Bissau',
        nameFR: 'Guinée-Bissau',
        nameEN: 'Guinea-Bissau',
        code: 'GNB',
        flag: '🇬🇼',
        logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/b/b4/Guinea-Bissau_Football_Federation_logo.png/200px-Guinea-Bissau_Football_Federation_logo.png',
        federation: 'FFGB - Federação de Futebol da Guiné-Bissau',
        site: 'www.ffgb.org',
        email: 'ffgb@ffgb.org',
        president: 'Nascimento Gomes',
        founded: 1974,
        fifaMember: 1986,
        confederation: 'CAF',
        colors: ['#CE1126', '#FCD116', '#009E60', '#000000'],
        path: 'app-universal-simple.html?club=Guinée-Bissau&logo=🇬🇼&sport=Football+Federation&league=CAF',
        region: 'Afrique de l\'Ouest'
    },
    {
        name: 'Guinée équatoriale',
        nameFR: 'Guinée équatoriale',
        nameEN: 'Equatorial Guinea',
        code: 'EQG',
        flag: '🇬🇶',
        logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/3/37/Equatorial_Guinea_Football_Federation_logo.png/200px-Equatorial_Guinea_Football_Federation_logo.png',
        federation: 'FEGUIFUT - Federación Ecuatoguineana de Fútbol',
        site: 'www.feguifut.com',
        email: 'feguifut@feguifut.com',
        president: 'Gustavo Ndong Edu',
        founded: 1960,
        fifaMember: 1986,
        confederation: 'CAF',
        colors: ['#3E9A00', '#FFFFFF', '#D21034', '#0072C6'],
        path: 'app-universal-simple.html?club=Guinée+équatoriale&logo=🇬🇶&sport=Football+Federation&league=CAF',
        region: 'Afrique Centrale'
    },
    {
        name: 'Kenya',
        nameFR: 'Kenya',
        nameEN: 'Kenya',
        code: 'KEN',
        flag: '🇰🇪',
        logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/4/46/Football_Kenya_Federation_logo.svg/200px-Football_Kenya_Federation_logo.svg.png',
        federation: 'FKF - Football Kenya Federation',
        site: 'www.footballkenya.org',
        email: 'fkf@footballkenya.org',
        president: 'Nick Mwendwa',
        founded: 1960,
        fifaMember: 1960,
        confederation: 'CAF',
        colors: ['#000000', '#BA0C2F', '#006600', '#FFFFFF'],
        path: 'app-universal-simple.html?club=Kenya&logo=🇰🇪&sport=Football+Federation&league=CAF',
        region: 'Afrique de l\'Est'
    },
    {
        name: 'Lesotho',
        nameFR: 'Lesotho',
        nameEN: 'Lesotho',
        code: 'LES',
        flag: '🇱🇸',
        logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/f/f7/Lesotho_Football_Association_logo.png/200px-Lesotho_Football_Association_logo.png',
        federation: 'LEFA - Lesotho Football Association',
        site: 'www.lfa.org.ls',
        email: 'lfa@lfa.org.ls',
        president: 'Salemane Phafane',
        founded: 1932,
        fifaMember: 1964,
        confederation: 'CAF',
        colors: ['#00209F', '#FFFFFF', '#009543'],
        path: 'app-universal-simple.html?club=Lesotho&logo=🇱🇸&sport=Football+Federation&league=CAF',
        region: 'Afrique Australe'
    },
    {
        name: 'Liberia',
        nameFR: 'Liberia',
        nameEN: 'Liberia',
        code: 'LBR',
        flag: '🇱🇷',
        logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/9/90/Liberia_Football_Association_logo.png/200px-Liberia_Football_Association_logo.png',
        federation: 'LFA - Liberia Football Association',
        site: 'www.lfa.org.lr',
        email: 'lfa@lfa.org.lr',
        president: 'Mustapha Raji',
        founded: 1936,
        fifaMember: 1964,
        confederation: 'CAF',
        colors: ['#BF0A30', '#002868', '#FFFFFF'],
        path: 'app-universal-simple.html?club=Liberia&logo=🇱🇷&sport=Football+Federation&league=CAF',
        region: 'Afrique de l\'Ouest'
    },
    {
        name: 'Libye',
        nameFR: 'Libye',
        nameEN: 'Libya',
        code: 'LBY',
        flag: '🇱🇾',
        logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/0/08/Libyan_Football_Federation_logo.svg/200px-Libyan_Football_Federation_logo.svg.png',
        federation: 'LFF - Libyan Football Federation',
        site: 'www.lff.ly',
        email: 'lff@lff.ly',
        president: 'Abdulhakim Al-Shalmani',
        founded: 1962,
        fifaMember: 1964,
        confederation: 'CAF',
        colors: ['#E70013', '#000000', '#239E46'],
        path: 'app-universal-simple.html?club=Libye&logo=🇱🇾&sport=Football+Federation&league=CAF',
        region: 'Afrique du Nord'
    },
    {
        name: 'Madagascar',
        nameFR: 'Madagascar',
        nameEN: 'Madagascar',
        code: 'MAD',
        flag: '🇲🇬',
        logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/e/ed/Malagasy_Football_Federation_logo.png/200px-Malagasy_Football_Federation_logo.png',
        federation: 'FMF - Fédération Malagasy de Football',
        site: 'www.fmf.mg',
        email: 'fmf@fmf.mg',
        president: 'Alfred Randriamanampisoa',
        founded: 1961,
        fifaMember: 1964,
        confederation: 'CAF',
        colors: ['#FC3D32', '#007E3A', '#FFFFFF'],
        path: 'app-universal-simple.html?club=Madagascar&logo=🇲🇬&sport=Football+Federation&league=CAF',
        region: 'Afrique de l\'Est'
    },
    {
        name: 'Malawi',
        nameFR: 'Malawi',
        nameEN: 'Malawi',
        code: 'MWI',
        flag: '🇲🇼',
        logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/9/90/Football_Association_of_Malawi_logo.svg/200px-Football_Association_of_Malawi_logo.svg.png',
        federation: 'FAM - Football Association of Malawi',
        site: 'www.fam.mw',
        email: 'fam@fam.mw',
        president: 'Walter Nyamilandu',
        founded: 1966,
        fifaMember: 1968,
        confederation: 'CAF',
        colors: ['#D10028', '#339E35', '#000000'],
        path: 'app-universal-simple.html?club=Malawi&logo=🇲🇼&sport=Football+Federation&league=CAF',
        region: 'Afrique Australe'
    },
    {
        name: 'Mali',
        nameFR: 'Mali',
        nameEN: 'Mali',
        code: 'MLI',
        flag: '🇲🇱',
        logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/c/cd/Mali_Football_Federation_logo.png/200px-Mali_Football_Federation_logo.png',
        federation: 'FEMAFOOT - Fédération Malienne de Football',
        site: 'www.femafoot.ml',
        email: 'femafoot@femafoot.ml',
        president: 'Mamoutou Touré',
        founded: 1960,
        fifaMember: 1964,
        confederation: 'CAF',
        colors: ['#14B53A', '#FCD116', '#CE1126'],
        path: 'app-universal-simple.html?club=Mali&logo=🇲🇱&sport=Football+Federation&league=CAF',
        region: 'Afrique de l\'Ouest'
    },
    {
        name: 'Maroc',
        nameFR: 'Maroc',
        nameEN: 'Morocco',
        code: 'MAR',
        flag: '🇲🇦',
        logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/6/68/Royal_Moroccan_Football_Federation_logo.svg/200px-Royal_Moroccan_Football_Federation_logo.svg.png',
        federation: 'FRMF - Fédération Royale Marocaine de Football',
        site: 'www.frmf.ma',
        email: 'frmf@frmf.ma',
        president: 'Fouzi Lekjaa',
        founded: 1955,
        fifaMember: 1960,
        confederation: 'CAF',
        colors: ['#C1272D', '#006233'],
        path: 'app-universal-simple.html?club=Maroc&logo=🇲🇦&sport=Football+Federation&league=CAF',
        region: 'Afrique du Nord'
    },
    {
        name: 'Maurice',
        nameFR: 'Maurice',
        nameEN: 'Mauritius',
        code: 'MRI',
        flag: '🇲🇺',
        logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/f/f3/Mauritius_Football_Association_logo.png/200px-Mauritius_Football_Association_logo.png',
        federation: 'MFA - Mauritius Football Association',
        site: 'www.mfa.mu',
        email: 'mfa@mfa.mu',
        president: 'Ahmed Patel',
        founded: 1952,
        fifaMember: 1964,
        confederation: 'CAF',
        colors: ['#EA2839', '#1A206D', '#FFD500', '#00A551'],
        path: 'app-universal-simple.html?club=Maurice&logo=🇲🇺&sport=Football+Federation&league=CAF',
        region: 'Afrique de l\'Est'
    },
    {
        name: 'Mauritanie',
        nameFR: 'Mauritanie',
        nameEN: 'Mauritania',
        code: 'MTN',
        flag: '🇲🇷',
        logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/2/2a/Mauritanian_Football_Federation_logo.png/200px-Mauritanian_Football_Federation_logo.png',
        federation: 'FFRIM - Fédération de Football de la République Islamique de Mauritanie',
        site: 'www.ffrim.mr',
        email: 'ffrim@ffrim.mr',
        president: 'Ahmed Ould Yahya',
        founded: 1961,
        fifaMember: 1964,
        confederation: 'CAF',
        colors: ['#00653E', '#FFD100'],
        path: 'app-universal-simple.html?club=Mauritanie&logo=🇲🇷&sport=Football+Federation&league=CAF',
        region: 'Afrique de l\'Ouest'
    },
    {
        name: 'Mozambique',
        nameFR: 'Mozambique',
        nameEN: 'Mozambique',
        code: 'MOZ',
        flag: '🇲🇿',
        logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/7/77/Mozambique_Football_Federation_logo.png/200px-Mozambique_Football_Federation_logo.png',
        federation: 'FFM - Federação Moçambicana de Futebol',
        site: 'www.ffm.co.mz',
        email: 'ffm@ffm.co.mz',
        president: 'Feizal Sidat',
        founded: 1975,
        fifaMember: 1980,
        confederation: 'CAF',
        colors: ['#007229', '#000000', '#FCE100', '#D21034'],
        path: 'app-universal-simple.html?club=Mozambique&logo=🇲🇿&sport=Football+Federation&league=CAF',
        region: 'Afrique Australe'
    },
    {
        name: 'Namibie',
        nameFR: 'Namibie',
        nameEN: 'Namibia',
        code: 'NAM',
        flag: '🇳🇦',
        logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/a/a4/Namibia_Football_Association_logo.png/200px-Namibia_Football_Association_logo.png',
        federation: 'NFA - Namibia Football Association',
        site: 'www.nfa.org.na',
        email: 'nfa@nfa.org.na',
        president: 'Frans Mbidi',
        founded: 1990,
        fifaMember: 1992,
        confederation: 'CAF',
        colors: ['#003580', '#009639', '#C8102E', '#FFD600'],
        path: 'app-universal-simple.html?club=Namibie&logo=🇳🇦&sport=Football+Federation&league=CAF',
        region: 'Afrique Australe'
    },
    {
        name: 'Niger',
        nameFR: 'Niger',
        nameEN: 'Niger',
        code: 'NIG',
        flag: '🇳🇪',
        logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/3/37/Niger_Football_Federation_logo.png/200px-Niger_Football_Federation_logo.png',
        federation: 'FENIFOOT - Fédération Nigérienne de Football',
        site: 'www.fenifoot.ne',
        email: 'fenifoot@fenifoot.ne',
        president: 'Daouda Sahidou Maigari',
        founded: 1967,
        fifaMember: 1967,
        confederation: 'CAF',
        colors: ['#E05206', '#0DB02B', '#FFFFFF'],
        path: 'app-universal-simple.html?club=Niger&logo=🇳🇪&sport=Football+Federation&league=CAF',
        region: 'Afrique de l\'Ouest'
    },
    {
        name: 'Nigeria',
        nameFR: 'Nigeria',
        nameEN: 'Nigeria',
        code: 'NGA',
        flag: '🇳🇬',
        logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/1/1f/Nigeria_Football_Federation_logo.svg/200px-Nigeria_Football_Federation_logo.svg.png',
        federation: 'NFF - Nigeria Football Federation',
        site: 'www.thenff.com',
        email: 'nff@thenff.com',
        president: 'Ibrahim Musa Gusau',
        founded: 1945,
        fifaMember: 1960,
        confederation: 'CAF',
        colors: ['#008751', '#FFFFFF'],
        path: 'app-universal-simple.html?club=Nigeria&logo=🇳🇬&sport=Football+Federation&league=CAF',
        region: 'Afrique de l\'Ouest'
    },
    {
        name: 'Ouganda',
        nameFR: 'Ouganda',
        nameEN: 'Uganda',
        code: 'UGA',
        flag: '🇺🇬',
        logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/4/4a/Uganda_Football_Association_logo.png/200px-Uganda_Football_Association_logo.png',
        federation: 'FUFA - Federation of Uganda Football Associations',
        site: 'www.fufa.co.ug',
        email: 'fufa@fufa.co.ug',
        president: 'Moses Magogo',
        founded: 1924,
        fifaMember: 1960,
        confederation: 'CAF',
        colors: ['#000000', '#FCDC04', '#D90000'],
        path: 'app-universal-simple.html?club=Ouganda&logo=🇺🇬&sport=Football+Federation&league=CAF',
        region: 'Afrique de l\'Est'
    },
    {
        name: 'Rwanda',
        nameFR: 'Rwanda',
        nameEN: 'Rwanda',
        code: 'RWA',
        flag: '🇷🇼',
        logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/e/eb/Rwanda_Football_Federation_logo.png/200px-Rwanda_Football_Federation_logo.png',
        federation: 'FERWAFA - Fédération Rwandaise de Football',
        site: 'www.ferwafa.rw',
        email: 'ferwafa@ferwafa.rw',
        president: 'Alphonse Munyantwari',
        founded: 1972,
        fifaMember: 1978,
        confederation: 'CAF',
        colors: ['#00A1DE', '#FAD201', '#20603D'],
        path: 'app-universal-simple.html?club=Rwanda&logo=🇷🇼&sport=Football+Federation&league=CAF',
        region: 'Afrique de l\'Est'
    },
    {
        name: 'Sao Tomé-et-Principe',
        nameFR: 'Sao Tomé-et-Principe',
        nameEN: 'São Tomé and Príncipe',
        code: 'STP',
        flag: '🇸🇹',
        logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/5/5a/S%C3%A3o_Tom%C3%A9_and_Pr%C3%ADncipe_Football_Federation_logo.png/200px-S%C3%A3o_Tom%C3%A9_and_Pr%C3%ADncipe_Football_Federation_logo.png',
        federation: 'FSF - Federação Santomense de Futebol',
        site: 'www.fsf.st',
        email: 'fsf@fsf.st',
        president: 'Rocha Costa',
        founded: 1975,
        fifaMember: 1986,
        confederation: 'CAF',
        colors: ['#12AD2B', '#FFCE00', '#D21034'],
        path: 'app-universal-simple.html?club=Sao+Tomé-et-Principe&logo=🇸🇹&sport=Football+Federation&league=CAF',
        region: 'Afrique Centrale'
    },
    {
        name: 'Sénégal',
        nameFR: 'Sénégal',
        nameEN: 'Senegal',
        code: 'SEN',
        flag: '🇸🇳',
        logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/3/31/Senegalese_Football_Federation_logo.svg/200px-Senegalese_Football_Federation_logo.svg.png',
        federation: 'FSF - Fédération Sénégalaise de Football',
        site: 'www.fsf.sn',
        email: 'fsf@fsf.sn',
        president: 'Augustin Senghor',
        founded: 1960,
        fifaMember: 1964,
        confederation: 'CAF',
        colors: ['#00853F', '#FCD116', '#E31B23'],
        path: 'app-universal-simple.html?club=Sénégal&logo=🇸🇳&sport=Football+Federation&league=CAF',
        region: 'Afrique de l\'Ouest'
    },
    {
        name: 'Seychelles',
        nameFR: 'Seychelles',
        nameEN: 'Seychelles',
        code: 'SEY',
        flag: '🇸🇨',
        logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/7/78/Seychelles_Football_Federation_logo.png/200px-Seychelles_Football_Federation_logo.png',
        federation: 'SFF - Seychelles Football Federation',
        site: 'www.sff.sc',
        email: 'sff@sff.sc',
        president: 'Elvis Chetty',
        founded: 1979,
        fifaMember: 1986,
        confederation: 'CAF',
        colors: ['#003F87', '#FCD116', '#D62612', '#FFFFFF', '#007A3D'],
        path: 'app-universal-simple.html?club=Seychelles&logo=🇸🇨&sport=Football+Federation&league=CAF',
        region: 'Afrique de l\'Est'
    },
    {
        name: 'Sierra Leone',
        nameFR: 'Sierra Leone',
        nameEN: 'Sierra Leone',
        code: 'SLE',
        flag: '🇸🇱',
        logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/a/a2/Sierra_Leone_Football_Association_logo.png/200px-Sierra_Leone_Football_Association_logo.png',
        federation: 'SLFA - Sierra Leone Football Association',
        site: 'www.slfa.sl',
        email: 'slfa@slfa.sl',
        president: 'Thomas Daddy Brima',
        founded: 1967,
        fifaMember: 1967,
        confederation: 'CAF',
        colors: ['#1EB53A', '#FFFFFF', '#0072C6'],
        path: 'app-universal-simple.html?club=Sierra+Leone&logo=🇸🇱&sport=Football+Federation&league=CAF',
        region: 'Afrique de l\'Ouest'
    },
    {
        name: 'Somalie',
        nameFR: 'Somalie',
        nameEN: 'Somalia',
        code: 'SOM',
        flag: '🇸🇴',
        logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/d/de/Somali_Football_Federation_logo.png/200px-Somali_Football_Federation_logo.png',
        federation: 'SFF - Somali Football Federation',
        site: 'www.sff.so',
        email: 'sff@sff.so',
        president: 'Abdiqani Said Arab',
        founded: 1951,
        fifaMember: 1962,
        confederation: 'CAF',
        colors: ['#4189DD', '#FFFFFF'],
        path: 'app-universal-simple.html?club=Somalie&logo=🇸🇴&sport=Football+Federation&league=CAF',
        region: 'Afrique de l\'Est'
    },
    {
        name: 'Soudan',
        nameFR: 'Soudan',
        nameEN: 'Sudan',
        code: 'SDN',
        flag: '🇸🇩',
        logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/a/ac/Sudan_Football_Association_logo.png/200px-Sudan_Football_Association_logo.png',
        federation: 'SFA - Sudan Football Association',
        site: 'www.sdnfa.sd',
        email: 'sdnfa@sdnfa.sd',
        president: 'Kamal Shaddad',
        founded: 1936,
        fifaMember: 1948,
        confederation: 'CAF',
        colors: ['#D21034', '#FFFFFF', '#000000', '#007229'],
        path: 'app-universal-simple.html?club=Soudan&logo=🇸🇩&sport=Football+Federation&league=CAF',
        region: 'Afrique de l\'Est'
    },
    {
        name: 'Soudan du Sud',
        nameFR: 'Soudan du Sud',
        nameEN: 'South Sudan',
        code: 'SSD',
        flag: '🇸🇸',
        logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/6/69/South_Sudan_Football_Association_logo.png/200px-South_Sudan_Football_Association_logo.png',
        federation: 'SSFA - South Sudan Football Association',
        site: 'www.ssfa.ss',
        email: 'ssfa@ssfa.ss',
        president: 'Augustino Maduot Parek',
        founded: 2011,
        fifaMember: 2012,
        confederation: 'CAF',
        colors: ['#000000', '#FFFFFF', '#DA121A', '#0F47AF', '#078930'],
        path: 'app-universal-simple.html?club=Soudan+du+Sud&logo=🇸🇸&sport=Football+Federation&league=CAF',
        region: 'Afrique de l\'Est'
    },
    {
        name: 'Tanzanie',
        nameFR: 'Tanzanie',
        nameEN: 'Tanzania',
        code: 'TAN',
        flag: '🇹🇿',
        logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/0/01/Tanzania_Football_Federation_logo.png/200px-Tanzania_Football_Federation_logo.png',
        federation: 'TFF - Tanzania Football Federation',
        site: 'www.tff.or.tz',
        email: 'tff@tff.or.tz',
        president: 'Wallace Karia',
        founded: 1930,
        fifaMember: 1964,
        confederation: 'CAF',
        colors: ['#1EB53A', '#FCD116', '#00A3DD', '#000000'],
        path: 'app-universal-simple.html?club=Tanzanie&logo=🇹🇿&sport=Football+Federation&league=CAF',
        region: 'Afrique de l\'Est'
    },
    {
        name: 'Tchad',
        nameFR: 'Tchad',
        nameEN: 'Chad',
        code: 'CHA',
        flag: '🇹🇩',
        logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/1/17/Chad_Football_Federation_logo.png/200px-Chad_Football_Federation_logo.png',
        federation: 'FTFA - Fédération Tchadienne de Football',
        site: 'www.ftfa.td',
        email: 'ftfa@ftfa.td',
        president: 'Mahmoud Al Khodher',
        founded: 1962,
        fifaMember: 1988,
        confederation: 'CAF',
        colors: ['#002664', '#FECB00', '#C60C30'],
        path: 'app-universal-simple.html?club=Tchad&logo=🇹🇩&sport=Football+Federation&league=CAF',
        region: 'Afrique Centrale'
    },
    {
        name: 'Togo',
        nameFR: 'Togo',
        nameEN: 'Togo',
        code: 'TOG',
        flag: '🇹🇬',
        logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/f/fb/Togo_Football_Federation_logo.png/200px-Togo_Football_Federation_logo.png',
        federation: 'FTF - Fédération Togolaise de Football',
        site: 'www.ftf.tg',
        email: 'ftf@ftf.tg',
        president: 'Guy-Ezan Akpaki',
        founded: 1960,
        fifaMember: 1962,
        confederation: 'CAF',
        colors: ['#006A4E', '#FFD100', '#D21034'],
        path: 'app-universal-simple.html?club=Togo&logo=🇹🇬&sport=Football+Federation&league=CAF',
        region: 'Afrique de l\'Ouest'
    },
    {
        name: 'Tunisie',
        nameFR: 'Tunisie',
        nameEN: 'Tunisia',
        code: 'TUN',
        flag: '🇹🇳',
        logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/b/b4/Tunisian_Football_Federation_logo.svg/200px-Tunisian_Football_Federation_logo.svg.png',
        federation: 'FTF - Fédération Tunisienne de Football',
        site: 'www.ftf.org.tn',
        email: 'ftf@ftf.org.tn',
        president: 'Wadii Jarii',
        founded: 1957,
        fifaMember: 1960,
        confederation: 'CAF',
        colors: ['#E70013', '#FFFFFF'],
        path: 'app-universal-simple.html?club=Tunisie&logo=🇹🇳&sport=Football+Federation&league=CAF',
        region: 'Afrique du Nord'
    },
    {
        name: 'Zambie',
        nameFR: 'Zambie',
        nameEN: 'Zambia',
        code: 'ZAM',
        flag: '🇿🇲',
        logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/1/1d/Football_Association_of_Zambia_logo.svg/200px-Football_Association_of_Zambia_logo.svg.png',
        federation: 'FAZ - Football Association of Zambia',
        site: 'www.faz.org.zm',
        email: 'faz@faz.org.zm',
        president: 'Andrew Kamanga',
        founded: 1929,
        fifaMember: 1964,
        confederation: 'CAF',
        colors: ['#198A00', '#EF7D00', '#000000', '#DE2010'],
        path: 'app-universal-simple.html?club=Zambie&logo=🇿🇲&sport=Football+Federation&league=CAF',
        region: 'Afrique Australe'
    },
    {
        name: 'Zimbabwe',
        nameFR: 'Zimbabwe',
        nameEN: 'Zimbabwe',
        code: 'ZIM',
        flag: '🇿🇼',
        logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/8/8d/Zimbabwe_Football_Association_logo.png/200px-Zimbabwe_Football_Association_logo.png',
        federation: 'ZIFA - Zimbabwe Football Association',
        site: 'www.zifa.org.zw',
        email: 'zifa@zifa.org.zw',
        president: 'Lincoln Mutasa',
        founded: 1965,
        fifaMember: 1965,
        confederation: 'CAF',
        colors: ['#007A4D', '#FFC726', '#DA121A', '#000000'],
        path: 'app-universal-simple.html?club=Zimbabwe&logo=🇿🇼&sport=Football+Federation&league=CAF',
        region: 'Afrique Australe'
    }
];

// ========== STATISTIQUES CAF ==========
const cafStats = {
    totalFederations: 54,
    regions: {
        'Afrique du Nord': 5,
        'Afrique de l\'Ouest': 16,
        'Afrique Centrale': 9,
        'Afrique de l\'Est': 14,
        'Afrique Australe': 10
    },
    founded: '1957',
    headquarters: 'Le Caire, Égypte',
    president: 'Patrice Motsepe',
    website: 'www.cafonline.com'
};

// ========== EXPORT ==========
console.log('✅ CAF - 54 FÉDÉRATIONS CHARGÉES AVEC LOGOS');
console.log(`🌍 Total: ${cafMembersWithLogos.length} associations membres`);
console.log('📊 Répartition régionale:', cafStats.regions);
console.log('🎯 Logos officiels intégrés depuis Wikimedia Commons');
