// ========== DONNÉES DES 41 ASSOCIATIONS MEMBRES DE LA CONCACAF ==========
const concacafMembersWithLogos = [
    // CFU - Caraïbes
    { name: "Anguilla", code: "AIA", flag: "🇦🇮", region: "CFU", president: "Raymond Guishard", founded: "1990", fifaMember: "1996", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/FIFA_logo_%28black%29.svg/200px-FIFA_logo_%28black%29.svg.png", path: "app-universal-simple.html?club=Anguilla&logo=🇦🇮&sport=Football+Federation&league=CONCACAF" },
    { name: "Antigua-et-Barbuda", code: "ATG", flag: "🇦🇬", region: "CFU", president: "Everton Gonsalves", founded: "1928", fifaMember: "1970", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/FIFA_logo_%28black%29.svg/200px-FIFA_logo_%28black%29.svg.png", path: "app-universal-simple.html?club=Antigua-et-Barbuda&logo=🇦🇬&sport=Football+Federation&league=CONCACAF" },
    { name: "Aruba", code: "ARU", flag: "🇦🇼", region: "CFU", president: "Ady Thijsen", founded: "1932", fifaMember: "1988", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/FIFA_logo_%28black%29.svg/200px-FIFA_logo_%28black%29.svg.png", path: "app-universal-simple.html?club=Aruba&logo=🇦🇼&sport=Football+Federation&league=CONCACAF" },
    { name: "Bahamas", code: "BAH", flag: "🇧🇸", region: "CFU", president: "Anton Sealey", founded: "1967", fifaMember: "1968", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/FIFA_logo_%28black%29.svg/200px-FIFA_logo_%28black%29.svg.png", path: "app-universal-simple.html?club=Bahamas&logo=🇧🇸&sport=Football+Federation&league=CONCACAF" },
    { name: "Barbade", code: "BRB", flag: "🇧🇧", region: "CFU", president: "Randy Harris", founded: "1910", fifaMember: "1968", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/FIFA_logo_%28black%29.svg/200px-FIFA_logo_%28black%29.svg.png", path: "app-universal-simple.html?club=Barbade&logo=🇧🇧&sport=Football+Federation&league=CONCACAF" },
    { name: "Bermudes", code: "BER", flag: "🇧🇲", region: "CFU", president: "Mark Wade", founded: "1928", fifaMember: "1962", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/FIFA_logo_%28black%29.svg/200px-FIFA_logo_%28black%29.svg.png", path: "app-universal-simple.html?club=Bermudes&logo=🇧🇲&sport=Football+Federation&league=CONCACAF" },
    { name: "Îles Vierges britanniques", code: "VGB", flag: "🇻🇬", region: "CFU", president: "Andy Bickerton", founded: "1974", fifaMember: "1996", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/FIFA_logo_%28black%29.svg/200px-FIFA_logo_%28black%29.svg.png", path: "app-universal-simple.html?club=Îles+Vierges+britanniques&logo=🇻🇬&sport=Football+Federation&league=CONCACAF" },
    { name: "Îles Caïmans", code: "CAY", flag: "🇰🇾", region: "CFU", president: "Alfredo Whittaker", founded: "1966", fifaMember: "1992", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/FIFA_logo_%28black%29.svg/200px-FIFA_logo_%28black%29.svg.png", path: "app-universal-simple.html?club=Îles+Caïmans&logo=🇰🇾&sport=Football+Federation&league=CONCACAF" },
    { name: "Cuba", code: "CUB", flag: "🇨🇺", region: "CFU", president: "Oliet Rodríguez", founded: "1924", fifaMember: "1932", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/FIFA_logo_%28black%29.svg/200px-FIFA_logo_%28black%29.svg.png", path: "app-universal-simple.html?club=Cuba&logo=🇨🇺&sport=Football+Federation&league=CONCACAF" },
    { name: "Curaçao", code: "CUW", flag: "🇨🇼", region: "CFU", president: "Rignaal Francisca", founded: "1921", fifaMember: "1932", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/FIFA_logo_%28black%29.svg/200px-FIFA_logo_%28black%29.svg.png", path: "app-universal-simple.html?club=Curaçao&logo=🇨🇼&sport=Football+Federation&league=CONCACAF" },
    { name: "Dominique", code: "DMA", flag: "🇩🇲", region: "CFU", president: "Glen Jeffrey", founded: "1970", fifaMember: "1994", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/FIFA_logo_%28black%29.svg/200px-FIFA_logo_%28black%29.svg.png", path: "app-universal-simple.html?club=Dominique&logo=🇩🇲&sport=Football+Federation&league=CONCACAF" },
    { name: "République dominicaine", code: "DOM", flag: "🇩🇴", region: "CFU", president: "Rubén García", founded: "1953", fifaMember: "1958", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/FIFA_logo_%28black%29.svg/200px-FIFA_logo_%28black%29.svg.png", path: "app-universal-simple.html?club=République+dominicaine&logo=🇩🇴&sport=Football+Federation&league=CONCACAF" },
    { name: "Grenade", code: "GRN", flag: "🇬🇩", region: "CFU", president: "Cheney Joseph", founded: "1924", fifaMember: "1978", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/FIFA_logo_%28black%29.svg/200px-FIFA_logo_%28black%29.svg.png", path: "app-universal-simple.html?club=Grenade&logo=🇬🇩&sport=Football+Federation&league=CONCACAF" },
    { name: "Guyana", code: "GUY", flag: "🇬🇾", region: "CFU", president: "Wayne Forde", founded: "1902", fifaMember: "1970", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/FIFA_logo_%28black%29.svg/200px-FIFA_logo_%28black%29.svg.png", path: "app-universal-simple.html?club=Guyana&logo=🇬🇾&sport=Football+Federation&league=CONCACAF" },
    { name: "Haïti", code: "HAI", flag: "🇭🇹", region: "CFU", president: "Yves Jean-Bart", founded: "1904", fifaMember: "1934", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/FIFA_logo_%28black%29.svg/200px-FIFA_logo_%28black%29.svg.png", path: "app-universal-simple.html?club=Haïti&logo=🇭🇹&sport=Football+Federation&league=CONCACAF" },
    { name: "Jamaïque", code: "JAM", flag: "🇯🇲", region: "CFU", president: "Michael Ricketts", founded: "1910", fifaMember: "1962", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/FIFA_logo_%28black%29.svg/200px-FIFA_logo_%28black%29.svg.png", path: "app-universal-simple.html?club=Jamaïque&logo=🇯🇲&sport=Football+Federation&league=CONCACAF" },
    { name: "Montserrat", code: "MSR", flag: "🇲🇸", region: "CFU", president: "Vincent Cassell", founded: "1973", fifaMember: "1996", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/FIFA_logo_%28black%29.svg/200px-FIFA_logo_%28black%29.svg.png", path: "app-universal-simple.html?club=Montserrat&logo=🇲🇸&sport=Football+Federation&league=CONCACAF" },
    { name: "Porto Rico", code: "PUR", flag: "🇵🇷", region: "CFU", president: "Ramón Soler", founded: "1940", fifaMember: "1960", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/FIFA_logo_%28black%29.svg/200px-FIFA_logo_%28black%29.svg.png", path: "app-universal-simple.html?club=Porto+Rico&logo=🇵🇷&sport=Football+Federation&league=CONCACAF" },
    { name: "Saint-Christophe-et-Niévès", code: "SKN", flag: "🇰🇳", region: "CFU", president: "Atiba Harris", founded: "1932", fifaMember: "1992", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/FIFA_logo_%28black%29.svg/200px-FIFA_logo_%28black%29.svg.png", path: "app-universal-simple.html?club=Saint-Christophe-et-Niévès&logo=🇰🇳&sport=Football+Federation&league=CONCACAF" },
    { name: "Sainte-Lucie", code: "LCA", flag: "🇱🇨", region: "CFU", president: "Lyndon Cooper", founded: "1979", fifaMember: "1988", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/FIFA_logo_%28black%29.svg/200px-FIFA_logo_%28black%29.svg.png", path: "app-universal-simple.html?club=Sainte-Lucie&logo=🇱🇨&sport=Football+Federation&league=CONCACAF" },
    { name: "Saint-Vincent-et-les-Grenadines", code: "VIN", flag: "🇻🇨", region: "CFU", president: "Venold Coombs", founded: "1979", fifaMember: "1988", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/FIFA_logo_%28black%29.svg/200px-FIFA_logo_%28black%29.svg.png", path: "app-universal-simple.html?club=Saint-Vincent-et-les-Grenadines&logo=🇻🇨&sport=Football+Federation&league=CONCACAF" },
    { name: "Suriname", code: "SUR", flag: "🇸🇷", region: "CFU", president: "John Krishnadath", founded: "1920", fifaMember: "1929", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/FIFA_logo_%28black%29.svg/200px-FIFA_logo_%28black%29.svg.png", path: "app-universal-simple.html?club=Suriname&logo=🇸🇷&sport=Football+Federation&league=CONCACAF" },
    { name: "Trinité-et-Tobago", code: "TRI", flag: "🇹🇹", region: "CFU", president: "Kieron Edwards", founded: "1908", fifaMember: "1964", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/FIFA_logo_%28black%29.svg/200px-FIFA_logo_%28black%29.svg.png", path: "app-universal-simple.html?club=Trinité-et-Tobago&logo=🇹🇹&sport=Football+Federation&league=CONCACAF" },
    { name: "Îles Turques-et-Caïques", code: "TCA", flag: "🇹🇨", region: "CFU", president: "Sonia Fulford", founded: "1996", fifaMember: "1998", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/FIFA_logo_%28black%29.svg/200px-FIFA_logo_%28black%29.svg.png", path: "app-universal-simple.html?club=Îles+Turques-et-Caïques&logo=🇹🇨&sport=Football+Federation&league=CONCACAF" },
    { name: "Îles Vierges américaines", code: "VIR", flag: "🇻🇮", region: "CFU", president: "Hillaren Frederick", founded: "1992", fifaMember: "1998", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/FIFA_logo_%28black%29.svg/200px-FIFA_logo_%28black%29.svg.png", path: "app-universal-simple.html?club=Îles+Vierges+américaines&logo=🇻🇮&sport=Football+Federation&league=CONCACAF" },
    
    // NAFU - Amérique du Nord
    { name: "Canada", code: "CAN", flag: "🇨🇦", region: "NAFU", president: "Nick Bontis", founded: "1912", fifaMember: "1913", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/FIFA_logo_%28black%29.svg/200px-FIFA_logo_%28black%29.svg.png", path: "app-universal-simple.html?club=Canada&logo=🇨🇦&sport=Football+Federation&league=CONCACAF" },
    { name: "Mexique", code: "MEX", flag: "🇲🇽", region: "NAFU", president: "Ivar Sisniega", founded: "1927", fifaMember: "1929", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/FIFA_logo_%28black%29.svg/200px-FIFA_logo_%28black%29.svg.png", path: "app-universal-simple.html?club=Mexique&logo=🇲🇽&sport=Football+Federation&league=CONCACAF" },
    { name: "États-Unis", code: "USA", flag: "🇺🇸", region: "NAFU", president: "Cindy Parlow Cone", founded: "1913", fifaMember: "1914", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/FIFA_logo_%28black%29.svg/200px-FIFA_logo_%28black%29.svg.png", path: "app-universal-simple.html?club=États-Unis&logo=🇺🇸&sport=Football+Federation&league=CONCACAF" },
    
    // UNCAF - Amérique Centrale
    { name: "Belize", code: "BLZ", flag: "🇧🇿", region: "UNCAF", president: "Sergio Chuc", founded: "1980", fifaMember: "1986", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/FIFA_logo_%28black%29.svg/200px-FIFA_logo_%28black%29.svg.png", path: "app-universal-simple.html?club=Belize&logo=🇧🇿&sport=Football+Federation&league=CONCACAF" },
    { name: "Costa Rica", code: "CRC", flag: "🇨🇷", region: "UNCAF", president: "Rodolfo Villalobos", founded: "1921", fifaMember: "1927", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/FIFA_logo_%28black%29.svg/200px-FIFA_logo_%28black%29.svg.png", path: "app-universal-simple.html?club=Costa+Rica&logo=🇨🇷&sport=Football+Federation&league=CONCACAF" },
    { name: "Salvador", code: "SLV", flag: "🇸🇻", region: "UNCAF", president: "Hugo Carrillo", founded: "1935", fifaMember: "1938", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/FIFA_logo_%28black%29.svg/200px-FIFA_logo_%28black%29.svg.png", path: "app-universal-simple.html?club=Salvador&logo=🇸🇻&sport=Football+Federation&league=CONCACAF" },
    { name: "Guatemala", code: "GUA", flag: "🇬🇹", region: "UNCAF", president: "Gerardo Paiz", founded: "1919", fifaMember: "1946", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/FIFA_logo_%28black%29.svg/200px-FIFA_logo_%28black%29.svg.png", path: "app-universal-simple.html?club=Guatemala&logo=🇬🇹&sport=Football+Federation&league=CONCACAF" },
    { name: "Honduras", code: "HON", flag: "🇭🇳", region: "UNCAF", president: "Jorge Salomón", founded: "1951", fifaMember: "1951", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/FIFA_logo_%28black%29.svg/200px-FIFA_logo_%28black%29.svg.png", path: "app-universal-simple.html?club=Honduras&logo=🇭🇳&sport=Football+Federation&league=CONCACAF" },
    { name: "Nicaragua", code: "NCA", flag: "🇳🇮", region: "UNCAF", president: "Juan Saca", founded: "1931", fifaMember: "1950", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/FIFA_logo_%28black%29.svg/200px-FIFA_logo_%28black%29.svg.png", path: "app-universal-simple.html?club=Nicaragua&logo=🇳🇮&sport=Football+Federation&league=CONCACAF" },
    { name: "Panama", code: "PAN", flag: "🇵🇦", region: "UNCAF", president: "Manuel Arias", founded: "1937", fifaMember: "1938", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/FIFA_logo_%28black%29.svg/200px-FIFA_logo_%28black%29.svg.png", path: "app-universal-simple.html?club=Panama&logo=🇵🇦&sport=Football+Federation&league=CONCACAF" },
];
