#!/usr/bin/env python3
# -*- coding: utf-8 -*-

afc_data = """// ========== DONNÉES DES 47 ASSOCIATIONS MEMBRES DE L'AFC ==========
// Mise à jour: 29 décembre 2024
// Source: AFC.com et Wikipedia

const afcMembersWithLogos = [
    // WAFF - Asie de l'Ouest
    { name: "Bahreïn", code: "BHR", flag: "🇧🇭", region: "WAFF", president: "Sheikh Ali bin Khalifa Al Khalifa", founded: "1951", fifaMember: "1966", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/FIFA_logo_%28black%29.svg/200px-FIFA_logo_%28black%29.svg.png", path: "app-universal-simple.html?club=Bahreïn&logo=🇧🇭&sport=Football+Federation&league=AFC" },
    { name: "Irak", code: "IRQ", flag: "🇮🇶", region: "WAFF", president: "Adnan Dirjal", founded: "1948", fifaMember: "1950", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/FIFA_logo_%28black%29.svg/200px-FIFA_logo_%28black%29.svg.png", path: "app-universal-simple.html?club=Irak&logo=🇮🇶&sport=Football+Federation&league=AFC" },
    { name: "Jordanie", code: "JOR", flag: "🇯🇴", region: "WAFF", president: "Prince Ali bin Al Hussein", founded: "1949", fifaMember: "1958", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/FIFA_logo_%28black%29.svg/200px-FIFA_logo_%28black%29.svg.png", path: "app-universal-simple.html?club=Jordanie&logo=🇯🇴&sport=Football+Federation&league=AFC" },
    { name: "Koweït", code: "KUW", flag: "🇰🇼", region: "WAFF", president: "Ahmad Al-Yusuf Al-Sabah", founded: "1952", fifaMember: "1962", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/FIFA_logo_%28black%29.svg/200px-FIFA_logo_%28black%29.svg.png", path: "app-universal-simple.html?club=Koweït&logo=🇰🇼&sport=Football+Federation&league=AFC" },
    { name: "Liban", code: "LBN", flag: "🇱🇧", region: "WAFF", president: "Hashem Haidar", founded: "1933", fifaMember: "1935", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/FIFA_logo_%28black%29.svg/200px-FIFA_logo_%28black%29.svg.png", path: "app-universal-simple.html?club=Liban&logo=🇱🇧&sport=Football+Federation&league=AFC" },
    { name: "Oman", code: "OMA", flag: "🇴🇲", region: "WAFF", president: "Sheikh Salim bin Saeed Al Wahaibi", founded: "1978", fifaMember: "1980", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/FIFA_logo_%28black%29.svg/200px-FIFA_logo_%28black%29.svg.png", path: "app-universal-simple.html?club=Oman&logo=🇴🇲&sport=Football+Federation&league=AFC" },
    { name: "Palestine", code: "PLE", flag: "🇵🇸", region: "WAFF", president: "Jibril Rajoub", founded: "1928", fifaMember: "1998", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/FIFA_logo_%28black%29.svg/200px-FIFA_logo_%28black%29.svg.png", path: "app-universal-simple.html?club=Palestine&logo=🇵🇸&sport=Football+Federation&league=AFC" },
    { name: "Qatar", code: "QAT", flag: "🇶🇦", region: "WAFF", president: "Sheikh Hamad bin Khalifa bin Ahmed Al Thani", founded: "1960", fifaMember: "1970", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/FIFA_logo_%28black%29.svg/200px-FIFA_logo_%28black%29.svg.png", path: "app-universal-simple.html?club=Qatar&logo=🇶🇦&sport=Football+Federation&league=AFC" },
    { name: "Arabie saoudite", code: "KSA", flag: "🇸🇦", region: "WAFF", president: "Yasser Al-Misehal", founded: "1956", fifaMember: "1956", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/FIFA_logo_%28black%29.svg/200px-FIFA_logo_%28black%29.svg.png", path: "app-universal-simple.html?club=Arabie+saoudite&logo=🇸🇦&sport=Football+Federation&league=AFC" },
    { name: "Syrie", code: "SYR", flag: "🇸🇾", region: "WAFF", president: "Salah Ramadan", founded: "1936", fifaMember: "1937", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/FIFA_logo_%28black%29.svg/200px-FIFA_logo_%28black%29.svg.png", path: "app-universal-simple.html?club=Syrie&logo=🇸🇾&sport=Football+Federation&league=AFC" },
    { name: "Émirats arabes unis", code: "UAE", flag: "🇦🇪", region: "WAFF", president: "Sheikh Rashid bin Humaid Al Nuaimi", founded: "1971", fifaMember: "1972", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/FIFA_logo_%28black%29.svg/200px-FIFA_logo_%28black%29.svg.png", path: "app-universal-simple.html?club=Émirats+arabes+unis&logo=🇦🇪&sport=Football+Federation&league=AFC" },
    { name: "Yémen", code: "YEM", flag: "🇾🇪", region: "WAFF", president: "Ahmed Saleh Al-Eisy", founded: "1962", fifaMember: "1980", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/FIFA_logo_%28black%29.svg/200px-FIFA_logo_%28black%29.svg.png", path: "app-universal-simple.html?club=Yémen&logo=🇾🇪&sport=Football+Federation&league=AFC" },
    
    // EAFF - Asie de l'Est
    { name: "Chine", code: "CHN", flag: "🇨🇳", region: "EAFF", president: "Du Zhaocai", founded: "1924", fifaMember: "1931", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/FIFA_logo_%28black%29.svg/200px-FIFA_logo_%28black%29.svg.png", path: "app-universal-simple.html?club=Chine&logo=🇨🇳&sport=Football+Federation&league=AFC" },
    { name: "Guam", code: "GUM", flag: "🇬🇺", region: "EAFF", president: "Tino San Gil", founded: "1975", fifaMember: "1996", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/FIFA_logo_%28black%29.svg/200px-FIFA_logo_%28black%29.svg.png", path: "app-universal-simple.html?club=Guam&logo=🇬🇺&sport=Football+Federation&league=AFC" },
    { name: "Hong Kong", code: "HKG", flag: "🇭🇰", region: "EAFF", president: "Pui Kwan Kay", founded: "1914", fifaMember: "1954", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/FIFA_logo_%28black%29.svg/200px-FIFA_logo_%28black%29.svg.png", path: "app-universal-simple.html?club=Hong+Kong&logo=🇭🇰&sport=Football+Federation&league=AFC" },
    { name: "Japon", code: "JPN", flag: "🇯🇵", region: "EAFF", president: "Kozo Tashima", founded: "1921", fifaMember: "1929", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/FIFA_logo_%28black%29.svg/200px-FIFA_logo_%28black%29.svg.png", path: "app-universal-simple.html?club=Japon&logo=🇯🇵&sport=Football+Federation&league=AFC" },
    { name: "Corée du Nord", code: "PRK", flag: "🇰🇵", region: "EAFF", president: "Ri Yong-chol", founded: "1945", fifaMember: "1958", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/FIFA_logo_%28black%29.svg/200px-FIFA_logo_%28black%29.svg.png", path: "app-universal-simple.html?club=Corée+du+Nord&logo=🇰🇵&sport=Football+Federation&league=AFC" },
    { name: "Corée du Sud", code: "KOR", flag: "🇰🇷", region: "EAFF", president: "Chung Mong-gyu", founded: "1928", fifaMember: "1948", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/FIFA_logo_%28black%29.svg/200px-FIFA_logo_%28black%29.svg.png", path: "app-universal-simple.html?club=Corée+du+Sud&logo=🇰🇷&sport=Football+Federation&league=AFC" },
    { name: "Macao", code: "MAC", flag: "🇲🇴", region: "EAFF", president: "Pang Kam Weng", founded: "1939", fifaMember: "1976", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/FIFA_logo_%28black%29.svg/200px-FIFA_logo_%28black%29.svg.png", path: "app-universal-simple.html?club=Macao&logo=🇲🇴&sport=Football+Federation&league=AFC" },
    { name: "Mongolie", code: "MNG", flag: "🇲🇳", region: "EAFF", president: "Ganbaatar Amgalanbaatar", founded: "1959", fifaMember: "1998", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/FIFA_logo_%28black%29.svg/200px-FIFA_logo_%28black%29.svg.png", path: "app-universal-simple.html?club=Mongolie&logo=🇲🇳&sport=Football+Federation&league=AFC" },
    { name: "Taipei chinois", code: "TPE", flag: "🇹🇼", region: "EAFF", president: "Lin Hung-chuan", founded: "1936", fifaMember: "1954", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/FIFA_logo_%28black%29.svg/200px-FIFA_logo_%28black%29.svg.png", path: "app-universal-simple.html?club=Taipei+chinois&logo=🇹🇼&sport=Football+Federation&league=AFC" },
    
    // CAFA - Asie Centrale
    { name: "Afghanistan", code: "AFG", flag: "🇦🇫", region: "CAFA", president: "Ata Mohammad Noori", founded: "1922", fifaMember: "1948", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/FIFA_logo_%28black%29.svg/200px-FIFA_logo_%28black%29.svg.png", path: "app-universal-simple.html?club=Afghanistan&logo=🇦🇫&sport=Football+Federation&league=AFC" },
    { name: "Iran", code: "IRN", flag: "🇮🇷", region: "CAFA", president: "Mehdi Taj", founded: "1920", fifaMember: "1948", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/FIFA_logo_%28black%29.svg/200px-FIFA_logo_%28black%29.svg.png", path: "app-universal-simple.html?club=Iran&logo=🇮🇷&sport=Football+Federation&league=AFC" },
    { name: "Kirghizistan", code: "KGZ", flag: "🇰🇬", region: "CAFA", president: "Akyl Asanaliev", founded: "1992", fifaMember: "1994", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/FIFA_logo_%28black%29.svg/200px-FIFA_logo_%28black%29.svg.png", path: "app-universal-simple.html?club=Kirghizistan&logo=🇰🇬&sport=Football+Federation&league=AFC" },
    { name: "Tadjikistan", code: "TJK", flag: "🇹🇯", region: "CAFA", president: "Rustam Emomali", founded: "1936", fifaMember: "1994", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/FIFA_logo_%28black%29.svg/200px-FIFA_logo_%28black%29.svg.png", path: "app-universal-simple.html?club=Tadjikistan&logo=🇹🇯&sport=Football+Federation&league=AFC" },
    { name: "Turkménistan", code: "TKM", flag: "🇹🇲", region: "CAFA", president: "Gurbanmyrat Alyev", founded: "1992", fifaMember: "1994", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/FIFA_logo_%28black%29.svg/200px-FIFA_logo_%28black%29.svg.png", path: "app-universal-simple.html?club=Turkménistan&logo=🇹🇲&sport=Football+Federation&league=AFC" },
    { name: "Ouzbékistan", code: "UZB", flag: "🇺🇿", region: "CAFA", president: "Umid Akhmadjonov", founded: "1946", fifaMember: "1994", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/FIFA_logo_%28black%29.svg/200px-FIFA_logo_%28black%29.svg.png", path: "app-universal-simple.html?club=Ouzbékistan&logo=🇺🇿&sport=Football+Federation&league=AFC" },
    
    // SAFF - Asie du Sud
    { name: "Bangladesh", code: "BAN", flag: "🇧🇩", region: "SAFF", president: "Kazi Salahuddin", founded: "1972", fifaMember: "1974", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/FIFA_logo_%28black%29.svg/200px-FIFA_logo_%28black%29.svg.png", path: "app-universal-simple.html?club=Bangladesh&logo=🇧🇩&sport=Football+Federation&league=AFC" },
    { name: "Bhoutan", code: "BHU", flag: "🇧🇹", region: "SAFF", president: "Ugyen Tshering", founded: "1983", fifaMember: "2000", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/FIFA_logo_%28black%29.svg/200px-FIFA_logo_%28black%29.svg.png", path: "app-universal-simple.html?club=Bhoutan&logo=🇧🇹&sport=Football+Federation&league=AFC" },
    { name: "Inde", code: "IND", flag: "🇮🇳", region: "SAFF", president: "Kalyan Chaubey", founded: "1937", fifaMember: "1948", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/FIFA_logo_%28black%29.svg/200px-FIFA_logo_%28black%29.svg.png", path: "app-universal-simple.html?club=Inde&logo=🇮🇳&sport=Football+Federation&league=AFC" },
    { name: "Maldives", code: "MDV", flag: "🇲🇻", region: "SAFF", president: "Bassam Adeel Jaleel", founded: "1982", fifaMember: "1986", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/FIFA_logo_%28black%29.svg/200px-FIFA_logo_%28black%29.svg.png", path: "app-universal-simple.html?club=Maldives&logo=🇲🇻&sport=Football+Federation&league=AFC" },
    { name: "Népal", code: "NEP", flag: "🇳🇵", region: "SAFF", president: "Karma Tsering Sherpa", founded: "1951", fifaMember: "1970", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/FIFA_logo_%28black%29.svg/200px-FIFA_logo_%28black%29.svg.png", path: "app-universal-simple.html?club=Népal&logo=🇳🇵&sport=Football+Federation&league=AFC" },
    { name: "Pakistan", code: "PAK", flag: "🇵🇰", region: "SAFF", president: "Haroon Malik", founded: "1948", fifaMember: "1948", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/FIFA_logo_%28black%29.svg/200px-FIFA_logo_%28black%29.svg.png", path: "app-universal-simple.html?club=Pakistan&logo=🇵🇰&sport=Football+Federation&league=AFC" },
    { name: "Sri Lanka", code: "SRI", flag: "🇱🇰", region: "SAFF", president: "Jaswar Umar Lebbe", founded: "1939", fifaMember: "1950", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/FIFA_logo_%28black%29.svg/200px-FIFA_logo_%28black%29.svg.png", path: "app-universal-simple.html?club=Sri+Lanka&logo=🇱🇰&sport=Football+Federation&league=AFC" },
    
    // AFF - Asie du Sud-Est
    { name: "Australie", code: "AUS", flag: "🇦🇺", region: "AFF", president: "Chris Nikou", founded: "1961", fifaMember: "1963", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/FIFA_logo_%28black%29.svg/200px-FIFA_logo_%28black%29.svg.png", path: "app-universal-simple.html?club=Australie&logo=🇦🇺&sport=Football+Federation&league=AFC" },
    { name: "Brunei", code: "BRU", flag: "🇧🇳", region: "AFF", president: "Pengiran Matusin", founded: "1959", fifaMember: "1969", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/FIFA_logo_%28black%29.svg/200px-FIFA_logo_%28black%29.svg.png", path: "app-universal-simple.html?club=Brunei&logo=🇧🇳&sport=Football+Federation&league=AFC" },
    { name: "Cambodge", code: "CAM", flag: "🇰🇭", region: "AFF", president: "Sao Sokha", founded: "1933", fifaMember: "1953", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/FIFA_logo_%28black%29.svg/200px-FIFA_logo_%28black%29.svg.png", path: "app-universal-simple.html?club=Cambodge&logo=🇰🇭&sport=Football+Federation&league=AFC" },
    { name: "Indonésie", code: "IDN", flag: "🇮🇩", region: "AFF", president: "Erick Thohir", founded: "1930", fifaMember: "1952", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/FIFA_logo_%28black%29.svg/200px-FIFA_logo_%28black%29.svg.png", path: "app-universal-simple.html?club=Indonésie&logo=🇮🇩&sport=Football+Federation&league=AFC" },
    { name: "Laos", code: "LAO", flag: "🇱🇦", region: "AFF", president: "Viphet Sihachakr", founded: "1951", fifaMember: "1952", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/FIFA_logo_%28black%29.svg/200px-FIFA_logo_%28black%29.svg.png", path: "app-universal-simple.html?club=Laos&logo=🇱🇦&sport=Football+Federation&league=AFC" },
    { name: "Malaisie", code: "MAS", flag: "🇲🇾", region: "AFF", president: "Hamidin Mohd Amin", founded: "1933", fifaMember: "1954", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/FIFA_logo_%28black%29.svg/200px-FIFA_logo_%28black%29.svg.png", path: "app-universal-simple.html?club=Malaisie&logo=🇲🇾&sport=Football+Federation&league=AFC" },
    { name: "Myanmar", code: "MYA", flag: "🇲🇲", region: "AFF", president: "U Zaw Zaw", founded: "1947", fifaMember: "1948", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/FIFA_logo_%28black%29.svg/200px-FIFA_logo_%28black%29.svg.png", path: "app-universal-simple.html?club=Myanmar&logo=🇲🇲&sport=Football+Federation&league=AFC" },
    { name: "Philippines", code: "PHI", flag: "🇵🇭", region: "AFF", president: "Mariano Araneta", founded: "1907", fifaMember: "1928", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/FIFA_logo_%28black%29.svg/200px-FIFA_logo_%28black%29.svg.png", path: "app-universal-simple.html?club=Philippines&logo=🇵🇭&sport=Football+Federation&league=AFC" },
    { name: "Singapour", code: "SIN", flag: "🇸🇬", region: "AFF", president: "Lim Kia Tong", founded: "1892", fifaMember: "1952", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/FIFA_logo_%28black%29.svg/200px-FIFA_logo_%28black%29.svg.png", path: "app-universal-simple.html?club=Singapour&logo=🇸🇬&sport=Football+Federation&league=AFC" },
    { name: "Thaïlande", code: "THA", flag: "🇹🇭", region: "AFF", president: "Nualphan Lamsam", founded: "1916", fifaMember: "1925", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/FIFA_logo_%28black%29.svg/200px-FIFA_logo_%28black%29.svg.png", path: "app-universal-simple.html?club=Thaïlande&logo=🇹🇭&sport=Football+Federation&league=AFC" },
    { name: "Timor oriental", code: "TLS", flag: "🇹🇱", region: "AFF", president: "Francisco Kalbuadi Lay", founded: "2002", fifaMember: "2005", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/FIFA_logo_%28black%29.svg/200px-FIFA_logo_%28black%29.svg.png", path: "app-universal-simple.html?club=Timor+oriental&logo=🇹🇱&sport=Football+Federation&league=AFC" },
    { name: "Vietnam", code: "VIE", flag: "🇻🇳", region: "AFF", president: "Tran Quoc Tuan", founded: "1962", fifaMember: "1964", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/FIFA_logo_%28black%29.svg/200px-FIFA_logo_%28black%29.svg.png", path: "app-universal-simple.html?club=Vietnam&logo=🇻🇳&sport=Football+Federation&league=AFC" },
];
"""

with open('🌍_AFC_MEMBERS.js', 'w', encoding='utf-8') as f:
    f.write(afc_data)

print("✅ Fichier AFC créé avec 47 associations")
