// ========== DONNÉES DES 10 ASSOCIATIONS MEMBRES DE LA CONMEBOL ==========
// Mise à jour: 29 décembre 2024
// Source: CONMEBOL.com et Wikipedia

const conmebolMembersWithLogos = [
    { name: "Argentine", code: "ARG", flag: "🇦🇷", president: "Claudio Tapia", founded: "1893", fifaMember: "1912", conmebolMember: "1916", logo: "https://upload.wikimedia.org/wikipedia/en/thumb/c/ce/Asociaci%C3%B3n_del_F%C3%BAtbol_Argentino_logo.svg/200px-Asociaci%C3%B3n_del_F%C3%BAtbol_Argentino_logo.svg.png", path: "app-universal-simple.html?club=Argentine&logo=🇦🇷&sport=Football+Federation&league=CONMEBOL" },
    { name: "Bolivie", code: "BOL", flag: "🇧🇴", president: "Fernando Costa", founded: "1925", fifaMember: "1926", conmebolMember: "1926", logo: "https://upload.wikimedia.org/wikipedia/en/thumb/9/9c/Federaci%C3%B3n_Boliviana_de_F%C3%BAtbol_logo.svg/200px-Federaci%C3%B3n_Boliviana_de_F%C3%BAtbol_logo.svg.png", path: "app-universal-simple.html?club=Bolivie&logo=🇧🇴&sport=Football+Federation&league=CONMEBOL" },
    { name: "Brésil", code: "BRA", flag: "🇧🇷", president: "Ednaldo Rodrigues", founded: "1914", fifaMember: "1923", conmebolMember: "1916", logo: "https://upload.wikimedia.org/wikipedia/en/thumb/e/e3/CBF_logo.svg/200px-CBF_logo.svg.png", path: "app-universal-simple.html?club=Brésil&logo=🇧🇷&sport=Football+Federation&league=CONMEBOL" },
    { name: "Chili", code: "CHI", flag: "🇨🇱", president: "Pablo Milad", founded: "1895", fifaMember: "1913", conmebolMember: "1916", logo: "https://upload.wikimedia.org/wikipedia/en/thumb/f/f4/Federaci%C3%B3n_de_F%C3%BAtbol_de_Chile_logo.svg/200px-Federaci%C3%B3n_de_F%C3%BAtbol_de_Chile_logo.svg.png", path: "app-universal-simple.html?club=Chili&logo=🇨🇱&sport=Football+Federation&league=CONMEBOL" },
    { name: "Colombie", code: "COL", flag: "🇨🇴", president: "Ramón Jesurún", founded: "1924", fifaMember: "1936", conmebolMember: "1936", logo: "https://upload.wikimedia.org/wikipedia/en/thumb/9/99/Federaci%C3%B3n_Colombiana_de_F%C3%BAtbol_logo.svg/200px-Federaci%C3%B3n_Colombiana_de_F%C3%BAtbol_logo.svg.png", path: "app-universal-simple.html?club=Colombie&logo=🇨🇴&sport=Football+Federation&league=CONMEBOL" },
    { name: "Équateur", code: "ECU", flag: "🇪🇨", president: "Francisco Egas", founded: "1925", fifaMember: "1926", conmebolMember: "1927", logo: "https://upload.wikimedia.org/wikipedia/en/thumb/c/cd/Ecuadorian_Football_Federation_logo.svg/200px-Ecuadorian_Football_Federation_logo.svg.png", path: "app-universal-simple.html?club=Équateur&logo=🇪🇨&sport=Football+Federation&league=CONMEBOL" },
    { name: "Paraguay", code: "PAR", flag: "🇵🇾", president: "Robert Harrison", founded: "1906", fifaMember: "1921", conmebolMember: "1921", logo: "https://upload.wikimedia.org/wikipedia/en/thumb/2/22/Asociaci%C3%B3n_Paraguaya_de_F%C3%BAtbol_logo.svg/200px-Asociaci%C3%B3n_Paraguaya_de_F%C3%BAtbol_logo.svg.png", path: "app-universal-simple.html?club=Paraguay&logo=🇵🇾&sport=Football+Federation&league=CONMEBOL" },
    { name: "Pérou", code: "PER", flag: "🇵🇪", president: "Agustín Lozano", founded: "1922", fifaMember: "1924", conmebolMember: "1925", logo: "https://upload.wikimedia.org/wikipedia/en/thumb/0/0f/Peruvian_Football_Federation_logo.svg/200px-Peruvian_Football_Federation_logo.svg.png", path: "app-universal-simple.html?club=Pérou&logo=🇵🇪&sport=Football+Federation&league=CONMEBOL" },
    { name: "Uruguay", code: "URU", flag: "🇺🇾", president: "Ignacio Alonso", founded: "1900", fifaMember: "1923", conmebolMember: "1916", logo: "https://upload.wikimedia.org/wikipedia/en/thumb/7/7b/Asociaci%C3%B3n_Uruguaya_de_F%C3%BAtbol_logo.svg/200px-Asociaci%C3%B3n_Uruguaya_de_F%C3%BAtbol_logo.svg.png", path: "app-universal-simple.html?club=Uruguay&logo=🇺🇾&sport=Football+Federation&league=CONMEBOL" },
    { name: "Venezuela", code: "VEN", flag: "🇻🇪", president: "Jorge Giménez", founded: "1926", fifaMember: "1952", conmebolMember: "1952", logo: "https://upload.wikimedia.org/wikipedia/en/thumb/5/53/Federaci%C3%B3n_Venezolana_de_F%C3%BAtbol_logo.svg/200px-Federaci%C3%B3n_Venezolana_de_F%C3%BAtbol_logo.svg.png", path: "app-universal-simple.html?club=Venezuela&logo=🇻🇪&sport=Football+Federation&league=CONMEBOL" },
];
