// ========================================
// CAF - CONFÉDÉRATION AFRICAINE DE FOOTBALL
// 54 Associations Membres Officielles
// Source : https://www.cafonline.com/fr/a-propos-de-la-caf/associations-membres/
// Logos officiels intégrés
// ========================================

const federationsCAF = [
    {
        name: 'Afrique du Sud',
        code: 'RSA',
        flag: '🇿🇦',
        logo: 'https://www.cafonline.com/assets/images/flags/south-africa.png',
        federation: 'SAFA - South African Football Association',
        site: 'safa.net',
        email: 'info@safa.net',
        president: 'Danny Jordaan',
        founded: 1991,
        fifaMember: 1992,
        path: 'app-universal-simple.html?club=Afrique+du+Sud&logo=🇿🇦&sport=Football+Federation&league=CAF'
    },
    {
        name: 'Algérie',
        code: 'ALG',
        flag: '🇩🇿',
        logo: 'https://www.cafonline.com/assets/images/flags/algeria.png',
        federation: 'FAF - Fédération Algérienne de Football',
        site: 'faf.dz',
        email: 'contact@faf.dz',
        president: 'Walid Sadi',
        founded: 1962,
        fifaMember: 1963,
        path: 'app-universal-simple.html?club=Algérie&logo=🇩🇿&sport=Football+Federation&league=CAF'
    },
    {
        name: 'Angola',
        code: 'ANG',
        flag: '🇦🇴',
        logo: 'https://www.cafonline.com/assets/images/flags/angola.png',
        federation: 'FAF - Federação Angolana de Futebol',
        site: 'faf.ao',
        email: 'faf@faf.ao',
        president: 'Artur de Almeida e Silva',
        founded: 1979,
        fifaMember: 1980,
        path: 'app-universal-simple.html?club=Angola&logo=🇦🇴&sport=Football+Federation&league=CAF'
    },
    {
        name: 'Bénin',
        code: 'BEN',
        flag: '🇧🇯',
        logo: 'https://www.cafonline.com/assets/images/flags/benin.png',
        federation: 'FBF - Fédération Béninoise de Football',
        site: 'fbf-benin.com',
        email: 'fbf@fbf-benin.com',
        president: 'Mathurin De Chacus',
        founded: 1962,
        fifaMember: 1962,
        path: 'app-universal-simple.html?club=Bénin&logo=🇧🇯&sport=Football+Federation&league=CAF'
    },
    {
        name: 'Botswana',
        code: 'BOT',
        flag: '🇧🇼',
        logo: 'https://www.cafonline.com/assets/images/flags/botswana.png',
        federation: 'BFA - Botswana Football Association',
        site: 'bfa.co.bw',
        email: 'bfa@bfa.co.bw',
        president: 'Maclean Letshwiti',
        founded: 1970,
        fifaMember: 1976,
        path: 'app-universal-simple.html?club=Botswana&logo=🇧🇼&sport=Football+Federation&league=CAF'
    },
    {
        name: 'Burkina Faso',
        code: 'BFA',
        flag: '🇧🇫',
        logo: 'https://www.cafonline.com/assets/images/flags/burkina-faso.png',
        federation: 'FBF - Fédération Burkinabè de Football',
        site: 'fbf.bf',
        email: 'fbf@fbf.bf',
        president: 'Lazare Banssé',
        founded: 1960,
        fifaMember: 1964,
        path: 'app-universal-simple.html?club=Burkina+Faso&logo=🇧🇫&sport=Football+Federation&league=CAF'
    },
    {
        name: 'Burundi',
        code: 'BDI',
        flag: '🇧🇮',
        logo: 'https://www.cafonline.com/assets/images/flags/burundi.png',
        federation: 'FFB - Fédération de Football du Burundi',
        site: 'ffb.bi',
        email: 'ffb@ffb.bi',
        president: 'Révérien Ndikuriyo',
        founded: 1948,
        fifaMember: 1972,
        path: 'app-universal-simple.html?club=Burundi&logo=🇧🇮&sport=Football+Federation&league=CAF'
    },
    {
        name: 'Cameroun',
        code: 'CMR',
        flag: '🇨🇲',
        logo: 'https://www.cafonline.com/assets/images/flags/cameroon.png',
        federation: 'FECAFOOT - Fédération Camerounaise de Football',
        site: 'fecafoot.cm',
        email: 'contact@fecafoot.cm',
        president: 'Samuel Eto\'o',
        founded: 1959,
        fifaMember: 1962,
        path: 'app-universal-simple.html?club=Cameroun&logo=🇨🇲&sport=Football+Federation&league=CAF'
    },
    {
        name: 'Cap-Vert',
        code: 'CPV',
        flag: '🇨🇻',
        logo: 'https://www.cafonline.com/assets/images/flags/cape-verde.png',
        federation: 'FCF - Federação Caboverdiana de Futebol',
        site: 'fcf.cv',
        email: 'fcf@fcf.cv',
        president: 'Mário Semedo',
        founded: 1982,
        fifaMember: 1986,
        path: 'app-universal-simple.html?club=Cap-Vert&logo=🇨🇻&sport=Football+Federation&league=CAF'
    },
    {
        name: 'Comores',
        code: 'COM',
        flag: '🇰🇲',
        logo: 'https://www.cafonline.com/assets/images/flags/comoros.png',
        federation: 'FFC - Fédération Comorienne de Football',
        site: 'ffc-comores.com',
        email: 'ffc@ffc-comores.com',
        president: 'Saïd Ali Saïd Attoumane',
        founded: 1979,
        fifaMember: 2005,
        path: 'app-universal-simple.html?club=Comores&logo=🇰🇲&sport=Football+Federation&league=CAF'
    },
    {
        name: 'Congo',
        code: 'CGO',
        flag: '🇨🇬',
        logo: 'https://www.cafonline.com/assets/images/flags/congo.png',
        federation: 'FECOFOOT - Fédération Congolaise de Football',
        site: 'fecofoot.com',
        email: 'fecofoot@fecofoot.com',
        president: 'Jean Guy Blaise Mayolas',
        founded: 1962,
        fifaMember: 1962,
        path: 'app-universal-simple.html?club=Congo&logo=🇨🇬&sport=Football+Federation&league=CAF'
    },
    {
        name: 'RD Congo',
        code: 'COD',
        flag: '🇨🇩',
        logo: 'https://www.cafonline.com/assets/images/flags/dr-congo.png',
        federation: 'FECOFA - Fédération Congolaise de Football-Association',
        site: 'fecofa.cd',
        email: 'fecofa@fecofa.cd',
        president: 'Constant Omari',
        founded: 1919,
        fifaMember: 1962,
        path: 'app-universal-simple.html?club=RD+Congo&logo=🇨🇩&sport=Football+Federation&league=CAF'
    },
    {
        name: 'Côte d\'Ivoire',
        code: 'CIV',
        flag: '🇨🇮',
        logo: 'https://www.cafonline.com/assets/images/flags/ivory-coast.png',
        federation: 'FIF - Fédération Ivoirienne de Football',
        site: 'fif.ci',
        email: 'fif@fif.ci',
        president: 'Yacine Idriss Diallo',
        founded: 1960,
        fifaMember: 1960,
        path: 'app-universal-simple.html?club=Côte+d%27Ivoire&logo=🇨🇮&sport=Football+Federation&league=CAF'
    },
    {
        name: 'Djibouti',
        code: 'DJI',
        flag: '🇩🇯',
        logo: 'https://www.cafonline.com/assets/images/flags/djibouti.png',
        federation: 'FFD - Fédération Djiboutienne de Football',
        site: 'ffd.dj',
        email: 'ffd@ffd.dj',
        president: 'Souleiman Hassan Waberi',
        founded: 1977,
        fifaMember: 1994,
        path: 'app-universal-simple.html?club=Djibouti&logo=🇩🇯&sport=Football+Federation&league=CAF'
    },
    {
        name: 'Égypte',
        code: 'EGY',
        flag: '🇪🇬',
        logo: 'https://www.cafonline.com/assets/images/flags/egypt.png',
        federation: 'EFA - Egyptian Football Association',
        site: 'efa.com.eg',
        email: 'efa@efa.com.eg',
        president: 'Ahmed Megahed',
        founded: 1921,
        fifaMember: 1923,
        path: 'app-universal-simple.html?club=Égypte&logo=🇪🇬&sport=Football+Federation&league=CAF'
    },
    {
        name: 'Érythrée',
        code: 'ERI',
        flag: '🇪🇷',
        logo: 'https://www.cafonline.com/assets/images/flags/eritrea.png',
        federation: 'EFA - Eritrean Football Federation',
        site: 'efifa.org',
        email: 'efifa@efifa.org',
        president: 'Ermias Yohannes',
        founded: 1996,
        fifaMember: 1998,
        path: 'app-universal-simple.html?club=Érythrée&logo=🇪🇷&sport=Football+Federation&league=CAF'
    },
    {
        name: 'Eswatini',
        code: 'SWZ',
        flag: '🇸🇿',
        logo: 'https://www.cafonline.com/assets/images/flags/eswatini.png',
        federation: 'EFA - Eswatini Football Association',
        site: 'sff.org.sz',
        email: 'sff@sff.org.sz',
        president: 'Peter Simelane',
        founded: 1968,
        fifaMember: 1978,
        path: 'app-universal-simple.html?club=Eswatini&logo=🇸🇿&sport=Football+Federation&league=CAF'
    },
    {
        name: 'Éthiopie',
        code: 'ETH',
        flag: '🇪🇹',
        logo: 'https://www.cafonline.com/assets/images/flags/ethiopia.png',
        federation: 'EFF - Ethiopian Football Federation',
        site: 'efa.et',
        email: 'efa@efa.et',
        president: 'Isayas Jira',
        founded: 1943,
        fifaMember: 1953,
        path: 'app-universal-simple.html?club=Éthiopie&logo=🇪🇹&sport=Football+Federation&league=CAF'
    },
    {
        name: 'Gabon',
        code: 'GAB',
        flag: '🇬🇦',
        logo: 'https://www.cafonline.com/assets/images/flags/gabon.png',
        federation: 'FEGAFOOT - Fédération Gabonaise de Football',
        site: 'fegafoot.com',
        email: 'fegafoot@fegafoot.com',
        president: 'Pierre Alain Mounguengui',
        founded: 1962,
        fifaMember: 1963,
        path: 'app-universal-simple.html?club=Gabon&logo=🇬🇦&sport=Football+Federation&league=CAF'
    },
    {
        name: 'Gambie',
        code: 'GMB',
        flag: '🇬🇲',
        logo: 'https://www.cafonline.com/assets/images/flags/gambia.png',
        federation: 'GFF - Gambia Football Federation',
        site: 'gff.gm',
        email: 'gff@gff.gm',
        president: 'Lamin Kaba Bajo',
        founded: 1952,
        fifaMember: 1966,
        path: 'app-universal-simple.html?club=Gambie&logo=🇬🇲&sport=Football+Federation&league=CAF'
    },
    {
        name: 'Ghana',
        code: 'GHA',
        flag: '🇬🇭',
        logo: 'https://www.cafonline.com/assets/images/flags/ghana.png',
        federation: 'GFA - Ghana Football Association',
        site: 'ghanafa.org',
        email: 'gfa@ghanafa.org',
        president: 'Kurt Okraku',
        founded: 1957,
        fifaMember: 1958,
        path: 'app-universal-simple.html?club=Ghana&logo=🇬🇭&sport=Football+Federation&league=CAF'
    },
    {
        name: 'Guinée',
        code: 'GUI',
        flag: '🇬🇳',
        logo: 'https://www.cafonline.com/assets/images/flags/guinea.png',
        federation: 'FEGUIFOOT - Fédération Guinéenne de Football',
        site: 'feguifoot.com',
        email: 'feguifoot@feguifoot.com',
        president: 'Aboubacar Sampil',
        founded: 1959,
        fifaMember: 1961,
        path: 'app-universal-simple.html?club=Guinée&logo=🇬🇳&sport=Football+Federation&league=CAF'
    },
    {
        name: 'Guinée-Bissau',
        code: 'GNB',
        flag: '🇬🇼',
        logo: 'https://www.cafonline.com/assets/images/flags/guinea-bissau.png',
        federation: 'FFGB - Federação de Futebol da Guiné-Bissau',
        site: 'ffgb.org',
        email: 'ffgb@ffgb.org',
        president: 'Nascimento Gomes',
        founded: 1974,
        fifaMember: 1986,
        path: 'app-universal-simple.html?club=Guinée-Bissau&logo=🇬🇼&sport=Football+Federation&league=CAF'
    },
    {
        name: 'Guinée équatoriale',
        code: 'EQG',
        flag: '🇬🇶',
        logo: 'https://www.cafonline.com/assets/images/flags/equatorial-guinea.png',
        federation: 'FEGUIFUT - Federación Ecuatoguineana de Fútbol',
        site: 'feguifut.com',
        email: 'feguifut@feguifut.com',
        president: 'Gustavo Ndong Edu',
        founded: 1960,
        fifaMember: 1986,
        path: 'app-universal-simple.html?club=Guinée+équatoriale&logo=🇬🇶&sport=Football+Federation&league=CAF'
    },
    {
        name: 'Kenya',
        code: 'KEN',
        flag: '🇰🇪',
        logo: 'https://www.cafonline.com/assets/images/flags/kenya.png',
        federation: 'FKF - Football Kenya Federation',
        site: 'footballkenya.org',
        email: 'fkf@footballkenya.org',
        president: 'Nick Mwendwa',
        founded: 1960,
        fifaMember: 1960,
        path: 'app-universal-simple.html?club=Kenya&logo=🇰🇪&sport=Football+Federation&league=CAF'
    },
    {
        name: 'Lesotho',
        code: 'LES',
        flag: '🇱🇸',
        logo: 'https://www.cafonline.com/assets/images/flags/lesotho.png',
        federation: 'LEFA - Lesotho Football Association',
        site: 'lfa.org.ls',
        email: 'lfa@lfa.org.ls',
        president: 'Salemane Phafane',
        founded: 1932,
        fifaMember: 1964,
        path: 'app-universal-simple.html?club=Lesotho&logo=🇱🇸&sport=Football+Federation&league=CAF'
    },
    {
        name: 'Liberia',
        code: 'LBR',
        flag: '🇱🇷',
        logo: 'https://www.cafonline.com/assets/images/flags/liberia.png',
        federation: 'LFA - Liberia Football Association',
        site: 'lfa.org.lr',
        email: 'lfa@lfa.org.lr',
        president: 'Mustapha Raji',
        founded: 1936,
        fifaMember: 1962,
        path: 'app-universal-simple.html?club=Liberia&logo=🇱🇷&sport=Football+Federation&league=CAF'
    },
    {
        name: 'Libye',
        code: 'LBY',
        flag: '🇱🇾',
        logo: 'https://www.cafonline.com/assets/images/flags/libya.png',
        federation: 'LFF - Libyan Football Federation',
        site: 'lff.ly',
        email: 'lff@lff.ly',
        president: 'Abdulhakim Al-Shalmani',
        founded: 1962,
        fifaMember: 1964,
        path: 'app-universal-simple.html?club=Libye&logo=🇱🇾&sport=Football+Federation&league=CAF'
    },
    {
        name: 'Madagascar',
        code: 'MAD',
        flag: '🇲🇬',
        logo: 'https://www.cafonline.com/assets/images/flags/madagascar.png',
        federation: 'FMF - Fédération Malgache de Football',
        site: 'fmf.mg',
        email: 'fmf@fmf.mg',
        president: 'Alfred Randriamanampisoa',
        founded: 1961,
        fifaMember: 1962,
        path: 'app-universal-simple.html?club=Madagascar&logo=🇲🇬&sport=Football+Federation&league=CAF'
    },
    {
        name: 'Malawi',
        code: 'MWI',
        flag: '🇲🇼',
        logo: 'https://www.cafonline.com/assets/images/flags/malawi.png',
        federation: 'FAM - Football Association of Malawi',
        site: 'fam.mw',
        email: 'fam@fam.mw',
        president: 'Walter Nyamilandu',
        founded: 1966,
        fifaMember: 1967,
        path: 'app-universal-simple.html?club=Malawi&logo=🇲🇼&sport=Football+Federation&league=CAF'
    },
    {
        name: 'Mali',
        code: 'MLI',
        flag: '🇲🇱',
        logo: 'https://www.cafonline.com/assets/images/flags/mali.png',
        federation: 'FEMAFOOT - Fédération Malienne de Football',
        site: 'femafoot.ml',
        email: 'femafoot@femafoot.ml',
        president: 'Mamoutou Touré',
        founded: 1960,
        fifaMember: 1962,
        path: 'app-universal-simple.html?club=Mali&logo=🇲🇱&sport=Football+Federation&league=CAF'
    },
    {
        name: 'Maroc',
        code: 'MAR',
        flag: '🇲🇦',
        logo: 'https://www.cafonline.com/assets/images/flags/morocco.png',
        federation: 'FRMF - Fédération Royale Marocaine de Football',
        site: 'frmf.ma',
        email: 'frmf@frmf.ma',
        president: 'Fouzi Lekjaa',
        founded: 1955,
        fifaMember: 1956,
        path: 'app-universal-simple.html?club=Maroc&logo=🇲🇦&sport=Football+Federation&league=CAF'
    },
    {
        name: 'Maurice',
        code: 'MRI',
        flag: '🇲🇺',
        logo: 'https://www.cafonline.com/assets/images/flags/mauritius.png',
        federation: 'MFA - Mauritius Football Association',
        site: 'mfa.mu',
        email: 'mfa@mfa.mu',
        president: 'Satyajit Boolell',
        founded: 1952,
        fifaMember: 1962,
        path: 'app-universal-simple.html?club=Maurice&logo=🇲🇺&sport=Football+Federation&league=CAF'
    },
    {
        name: 'Mauritanie',
        code: 'MTN',
        flag: '🇲🇷',
        logo: 'https://www.cafonline.com/assets/images/flags/mauritania.png',
        federation: 'FFRIM - Fédération de Football de la République Islamique de Mauritanie',
        site: 'ffrim.mr',
        email: 'ffrim@ffrim.mr',
        president: 'Ahmed Yahya',
        founded: 1961,
        fifaMember: 1964,
        path: 'app-universal-simple.html?club=Mauritanie&logo=🇲🇷&sport=Football+Federation&league=CAF'
    },
    {
        name: 'Mozambique',
        code: 'MOZ',
        flag: '🇲🇿',
        logo: 'https://www.cafonline.com/assets/images/flags/mozambique.png',
        federation: 'FFM - Federação Moçambicana de Futebol',
        site: 'ffm.co.mz',
        email: 'ffm@ffm.co.mz',
        president: 'Feizal Sidat',
        founded: 1975,
        fifaMember: 1978,
        path: 'app-universal-simple.html?club=Mozambique&logo=🇲🇿&sport=Football+Federation&league=CAF'
    },
    {
        name: 'Namibie',
        code: 'NAM',
        flag: '🇳🇦',
        logo: 'https://www.cafonline.com/assets/images/flags/namibia.png',
        federation: 'NFA - Namibia Football Association',
        site: 'nfa.org.na',
        email: 'nfa@nfa.org.na',
        president: 'Frans Mbidi',
        founded: 1990,
        fifaMember: 1992,
        path: 'app-universal-simple.html?club=Namibie&logo=🇳🇦&sport=Football+Federation&league=CAF'
    },
    {
        name: 'Niger',
        code: 'NIG',
        flag: '🇳🇪',
        logo: 'https://www.cafonline.com/assets/images/flags/niger.png',
        federation: 'FENIFOOT - Fédération Nigérienne de Football',
        site: 'fenifoot.ne',
        email: 'fenifoot@fenifoot.ne',
        president: 'Daouda Malam Wanké',
        founded: 1967,
        fifaMember: 1967,
        path: 'app-universal-simple.html?club=Niger&logo=🇳🇪&sport=Football+Federation&league=CAF'
    },
    {
        name: 'Nigeria',
        code: 'NGA',
        flag: '🇳🇬',
        logo: 'https://www.cafonline.com/assets/images/flags/nigeria.png',
        federation: 'NFF - Nigeria Football Federation',
        site: 'thenff.com',
        email: 'nff@thenff.com',
        president: 'Ibrahim Gusau',
        founded: 1945,
        fifaMember: 1959,
        path: 'app-universal-simple.html?club=Nigeria&logo=🇳🇬&sport=Football+Federation&league=CAF'
    },
    {
        name: 'Ouganda',
        code: 'UGA',
        flag: '🇺🇬',
        logo: 'https://www.cafonline.com/assets/images/flags/uganda.png',
        federation: 'FUFA - Federation of Uganda Football Associations',
        site: 'fufa.co.ug',
        email: 'fufa@fufa.co.ug',
        president: 'Moses Magogo',
        founded: 1924,
        fifaMember: 1959,
        path: 'app-universal-simple.html?club=Ouganda&logo=🇺🇬&sport=Football+Federation&league=CAF'
    },
    {
        name: 'Rwanda',
        code: 'RWA',
        flag: '🇷🇼',
        logo: 'https://www.cafonline.com/assets/images/flags/rwanda.png',
        federation: 'FERWAFA - Fédération Rwandaise de Football Association',
        site: 'ferwafa.rw',
        email: 'ferwafa@ferwafa.rw',
        president: 'Olivier Mugabo Nizeyimana',
        founded: 1972,
        fifaMember: 1976,
        path: 'app-universal-simple.html?club=Rwanda&logo=🇷🇼&sport=Football+Federation&league=CAF'
    },
    {
        name: 'Sao Tomé-et-Principe',
        code: 'STP',
        flag: '🇸🇹',
        logo: 'https://www.cafonline.com/assets/images/flags/sao-tome.png',
        federation: 'FSF - Federação Santomense de Futebol',
        site: 'fsf.st',
        email: 'fsf@fsf.st',
        president: 'Felisberto Alves',
        founded: 1975,
        fifaMember: 1986,
        path: 'app-universal-simple.html?club=Sao+Tomé-et-Principe&logo=🇸🇹&sport=Football+Federation&league=CAF'
    },
    {
        name: 'Sénégal',
        code: 'SEN',
        flag: '🇸🇳',
        logo: 'https://www.cafonline.com/assets/images/flags/senegal.png',
        federation: 'FSF - Fédération Sénégalaise de Football',
        site: 'fsf.sn',
        email: 'fsf@fsf.sn',
        president: 'Augustin Senghor',
        founded: 1960,
        fifaMember: 1962,
        path: 'app-universal-simple.html?club=Sénégal&logo=🇸🇳&sport=Football+Federation&league=CAF'
    },
    {
        name: 'Seychelles',
        code: 'SEY',
        flag: '🇸🇨',
        logo: 'https://www.cafonline.com/assets/images/flags/seychelles.png',
        federation: 'SFF - Seychelles Football Federation',
        site: 'sff.sc',
        email: 'sff@sff.sc',
        president: 'Elvis Chetty',
        founded: 1979,
        fifaMember: 1986,
        path: 'app-universal-simple.html?club=Seychelles&logo=🇸🇨&sport=Football+Federation&league=CAF'
    },
    {
        name: 'Sierra Leone',
        code: 'SLE',
        flag: '🇸🇱',
        logo: 'https://www.cafonline.com/assets/images/flags/sierra-leone.png',
        federation: 'SLFA - Sierra Leone Football Association',
        site: 'slfa.sl',
        email: 'slfa@slfa.sl',
        president: 'Thomas Daddy Brima',
        founded: 1923,
        fifaMember: 1967,
        path: 'app-universal-simple.html?club=Sierra+Leone&logo=🇸🇱&sport=Football+Federation&league=CAF'
    },
    {
        name: 'Somalie',
        code: 'SOM',
        flag: '🇸🇴',
        logo: 'https://www.cafonline.com/assets/images/flags/somalia.png',
        federation: 'SFF - Somali Football Federation',
        site: 'sff.so',
        email: 'sff@sff.so',
        president: 'Abdiqani Said Arab',
        founded: 1951,
        fifaMember: 1960,
        path: 'app-universal-simple.html?club=Somalie&logo=🇸🇴&sport=Football+Federation&league=CAF'
    },
    {
        name: 'Soudan',
        code: 'SDN',
        flag: '🇸🇩',
        logo: 'https://www.cafonline.com/assets/images/flags/sudan.png',
        federation: 'SFA - Sudan Football Association',
        site: 'sdnfa.sd',
        email: 'sdnfa@sdnfa.sd',
        president: 'Musa Hamdan',
        founded: 1936,
        fifaMember: 1948,
        path: 'app-universal-simple.html?club=Soudan&logo=🇸🇩&sport=Football+Federation&league=CAF'
    },
    {
        name: 'Soudan du Sud',
        code: 'SSD',
        flag: '🇸🇸',
        logo: 'https://www.cafonline.com/assets/images/flags/south-sudan.png',
        federation: 'SSFA - South Sudan Football Association',
        site: 'ssfa.ss',
        email: 'ssfa@ssfa.ss',
        president: 'Augustino Maduot Parek',
        founded: 2011,
        fifaMember: 2012,
        path: 'app-universal-simple.html?club=Soudan+du+Sud&logo=🇸🇸&sport=Football+Federation&league=CAF'
    },
    {
        name: 'Tanzanie',
        code: 'TAN',
        flag: '🇹🇿',
        logo: 'https://www.cafonline.com/assets/images/flags/tanzania.png',
        federation: 'TFF - Tanzania Football Federation',
        site: 'tff.or.tz',
        email: 'tff@tff.or.tz',
        president: 'Wallace Karia',
        founded: 1930,
        fifaMember: 1964,
        path: 'app-universal-simple.html?club=Tanzanie&logo=🇹🇿&sport=Football+Federation&league=CAF'
    },
    {
        name: 'Tchad',
        code: 'CHA',
        flag: '🇹🇩',
        logo: 'https://www.cafonline.com/assets/images/flags/chad.png',
        federation: 'FTFA - Fédération Tchadienne de Football',
        site: 'ftfa.td',
        email: 'ftfa@ftfa.td',
        president: 'Moctar Mahamoud',
        founded: 1962,
        fifaMember: 1988,
        path: 'app-universal-simple.html?club=Tchad&logo=🇹🇩&sport=Football+Federation&league=CAF'
    },
    {
        name: 'Togo',
        code: 'TOG',
        flag: '🇹🇬',
        logo: 'https://www.cafonline.com/assets/images/flags/togo.png',
        federation: 'FTF - Fédération Togolaise de Football',
        site: 'ftf.tg',
        email: 'ftf@ftf.tg',
        president: 'Guy-Akpéné Adzéto',
        founded: 1960,
        fifaMember: 1962,
        path: 'app-universal-simple.html?club=Togo&logo=🇹🇬&sport=Football+Federation&league=CAF'
    },
    {
        name: 'Tunisie',
        code: 'TUN',
        flag: '🇹🇳',
        logo: 'https://www.cafonline.com/assets/images/flags/tunisia.png',
        federation: 'FTF - Fédération Tunisienne de Football',
        site: 'ftf.org.tn',
        email: 'ftf@ftf.org.tn',
        president: 'Wadie Jary',
        founded: 1957,
        fifaMember: 1960,
        path: 'app-universal-simple.html?club=Tunisie&logo=🇹🇳&sport=Football+Federation&league=CAF'
    },
    {
        name: 'Zambie',
        code: 'ZAM',
        flag: '🇿🇲',
        logo: 'https://www.cafonline.com/assets/images/flags/zambia.png',
        federation: 'FAZ - Football Association of Zambia',
        site: 'faz.org.zm',
        email: 'faz@faz.org.zm',
        president: 'Andrew Kamanga',
        founded: 1929,
        fifaMember: 1964,
        path: 'app-universal-simple.html?club=Zambie&logo=🇿🇲&sport=Football+Federation&league=CAF'
    },
    {
        name: 'Zimbabwe',
        code: 'ZIM',
        flag: '🇿🇼',
        logo: 'https://www.cafonline.com/assets/images/flags/zimbabwe.png',
        federation: 'ZIFA - Zimbabwe Football Association',
        site: 'zifa.org.zw',
        email: 'zifa@zifa.org.zw',
        president: 'Lincoln Mutasa',
        founded: 1965,
        fifaMember: 1965,
        path: 'app-universal-simple.html?club=Zimbabwe&logo=🇿🇼&sport=Football+Federation&league=CAF'
    }
];

// Console log pour confirmation
console.log('✅ CAF - Fédérations officielles chargées:');
console.log('🌍 Total CAF:', federationsCAF.length, 'fédérations');
console.log('📊 Données complètes : Nom, Code, Flag, Logo CAF, Président, Année fondation, Membre FIFA');
