// ========== DONNÉES DES 55 FÉDÉRATIONS MEMBRES DE L'UEFA ==========
// Mise à jour: 29 décembre 2024
// Source: UEFA.com et Wikipedia

const uefaMembersWithLogos = [
    // EUROPE DE L'OUEST
    { name: "France", code: "FRA", flag: "🇫🇷", region: "Europe de l'Ouest", president: "Philippe Diallo", founded: "1919", fifaMember: "1904", uefaMember: "1954", logo: "https://upload.wikimedia.org/wikipedia/fr/thumb/1/12/Logo_FFF_2023.svg/200px-Logo_FFF_2023.svg.png", path: "app-universal-simple.html?club=France&logo=🇫🇷&sport=Football+Federation&league=UEFA" },
    { name: "Allemagne", code: "GER", flag: "🇩🇪", region: "Europe de l'Ouest", president: "Bernd Neuendorf", founded: "1900", fifaMember: "1904", uefaMember: "1954", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/DFB_Logo_2017.svg/200px-DFB_Logo_2017.svg.png", path: "app-universal-simple.html?club=Allemagne&logo=🇩🇪&sport=Football+Federation&league=UEFA" },
    { name: "Pays-Bas", code: "NED", flag: "🇳🇱", region: "Europe de l'Ouest", president: "Just Spee", founded: "1889", fifaMember: "1904", uefaMember: "1954", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Royal_Dutch_Football_Association_logo.svg/200px-Royal_Dutch_Football_Association_logo.svg.png", path: "app-universal-simple.html?club=Pays-Bas&logo=🇳🇱&sport=Football+Federation&league=UEFA" },
    { name: "Belgique", code: "BEL", flag: "🇧🇪", region: "Europe de l'Ouest", president: "Pascale Van Damme", founded: "1895", fifaMember: "1904", uefaMember: "1954", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/KBVB_URBSFA_logo.svg/200px-KBVB_URBSFA_logo.svg.png", path: "app-universal-simple.html?club=Belgique&logo=🇧🇪&sport=Football+Federation&league=UEFA" },
    { name: "Luxembourg", code: "LUX", flag: "🇱🇺", region: "Europe de l'Ouest", president: "Paul Philipp", founded: "1908", fifaMember: "1910", uefaMember: "1954", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6c/Logo_FLF.svg/200px-Logo_FLF.svg.png", path: "app-universal-simple.html?club=Luxembourg&logo=🇱🇺&sport=Football+Federation&league=UEFA" },
    { name: "Suisse", code: "SUI", flag: "🇨🇭", region: "Europe de l'Ouest", president: "Dominique Blanc", founded: "1895", fifaMember: "1904", uefaMember: "1954", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Swiss_Football_Association_logo.svg/200px-Swiss_Football_Association_logo.svg.png", path: "app-universal-simple.html?club=Suisse&logo=🇨🇭&sport=Football+Federation&league=UEFA" },
    { name: "Autriche", code: "AUT", flag: "🇦🇹", region: "Europe de l'Ouest", president: "Klaus Mitterdorfer", founded: "1904", fifaMember: "1905", uefaMember: "1954", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/%C3%96FB_logo.svg/200px-%C3%96FB_logo.svg.png", path: "app-universal-simple.html?club=Autriche&logo=🇦🇹&sport=Football+Federation&league=UEFA" },
    { name: "Liechtenstein", code: "LIE", flag: "🇱🇮", region: "Europe de l'Ouest", president: "Josef Biedermann", founded: "1934", fifaMember: "1974", uefaMember: "1974", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Liechtensteiner_Fussballverband_logo.svg/200px-Liechtensteiner_Fussballverband_logo.svg.png", path: "app-universal-simple.html?club=Liechtenstein&logo=🇱🇮&sport=Football+Federation&league=UEFA" },
    
    // EUROPE DU NORD
    { name: "Angleterre", code: "ENG", flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿", region: "Europe du Nord", president: "Debbie Hewitt", founded: "1863", fifaMember: "1905", uefaMember: "1954", logo: "https://upload.wikimedia.org/wikipedia/en/thumb/5/53/England_2009_crest.svg/200px-England_2009_crest.svg.png", path: "app-universal-simple.html?club=Angleterre&logo=🏴󠁧󠁢󠁥󠁮󠁧󠁿&sport=Football+Federation&league=UEFA" },
    { name: "Écosse", code: "SCO", flag: "🏴󠁧󠁢󠁳󠁣󠁴󠁿", region: "Europe du Nord", president: "Mike Mulraney", founded: "1873", fifaMember: "1910", uefaMember: "1954", logo: "https://upload.wikimedia.org/wikipedia/en/thumb/e/e5/Scottish_Football_Association.svg/200px-Scottish_Football_Association.svg.png", path: "app-universal-simple.html?club=Écosse&logo=🏴󠁧󠁢󠁳󠁣󠁴󠁿&sport=Football+Federation&league=UEFA" },
    { name: "Pays de Galles", code: "WAL", flag: "🏴󠁧󠁢󠁷󠁬󠁳󠁿", region: "Europe du Nord", president: "Steve Williams", founded: "1876", fifaMember: "1910", uefaMember: "1954", logo: "https://upload.wikimedia.org/wikipedia/en/thumb/d/d9/Football_Association_of_Wales_logo.svg/200px-Football_Association_of_Wales_logo.svg.png", path: "app-universal-simple.html?club=Pays+de+Galles&logo=🏴󠁧󠁢󠁷󠁬󠁳󠁿&sport=Football+Federation&league=UEFA" },
    { name: "Irlande du Nord", code: "NIR", flag: "🇬🇧", region: "Europe du Nord", president: "Conrad Kirkwood", founded: "1880", fifaMember: "1911", uefaMember: "1954", logo: "https://upload.wikimedia.org/wikipedia/en/thumb/c/ce/Irish_FA_logo.svg/200px-Irish_FA_logo.svg.png", path: "app-universal-simple.html?club=Irlande+du+Nord&logo=🇬🇧&sport=Football+Federation&league=UEFA" },
    { name: "République d'Irlande", code: "IRL", flag: "🇮🇪", region: "Europe du Nord", president: "Gerry McAnaney", founded: "1921", fifaMember: "1923", uefaMember: "1954", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Football_Association_of_Ireland_logo.svg/200px-Football_Association_of_Ireland_logo.svg.png", path: "app-universal-simple.html?club=République+d%27Irlande&logo=🇮🇪&sport=Football+Federation&league=UEFA" },
    { name: "Suède", code: "SWE", flag: "🇸🇪", region: "Europe du Nord", president: "Fredrik Reinfeldt", founded: "1904", fifaMember: "1904", uefaMember: "1954", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7c/Svenska_Fotbollf%C3%B6rbundet_logo.svg/200px-Svenska_Fotbollf%C3%B6rbundet_logo.svg.png", path: "app-universal-simple.html?club=Suède&logo=🇸🇪&sport=Football+Federation&league=UEFA" },
    { name: "Norvège", code: "NOR", flag: "🇳🇴", region: "Europe du Nord", president: "Lise Klaveness", founded: "1902", fifaMember: "1908", uefaMember: "1954", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Norges_Fotballforbund_logo.svg/200px-Norges_Fotballforbund_logo.svg.png", path: "app-universal-simple.html?club=Norvège&logo=🇳🇴&sport=Football+Federation&league=UEFA" },
    { name: "Danemark", code: "DEN", flag: "🇩🇰", region: "Europe du Nord", president: "Jesper Møller", founded: "1889", fifaMember: "1904", uefaMember: "1954", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/Danish_Football_Association_logo.svg/200px-Danish_Football_Association_logo.svg.png", path: "app-universal-simple.html?club=Danemark&logo=🇩🇰&sport=Football+Federation&league=UEFA" },
    { name: "Finlande", code: "FIN", flag: "🇫🇮", region: "Europe du Nord", president: "Ari Lahti", founded: "1907", fifaMember: "1908", uefaMember: "1954", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/Football_Association_of_Finland_logo.svg/200px-Football_Association_of_Finland_logo.svg.png", path: "app-universal-simple.html?club=Finlande&logo=🇫🇮&sport=Football+Federation&league=UEFA" },
    { name: "Islande", code: "ISL", flag: "🇮🇸", region: "Europe du Nord", president: "Guðni Bergsson", founded: "1947", fifaMember: "1947", uefaMember: "1954", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Football_Association_of_Iceland_logo.svg/200px-Football_Association_of_Iceland_logo.svg.png", path: "app-universal-simple.html?club=Islande&logo=🇮🇸&sport=Football+Federation&league=UEFA" },
    { name: "Îles Féroé", code: "FRO", flag: "🇫🇴", region: "Europe du Nord", president: "Heri Simonsen", founded: "1979", fifaMember: "1988", uefaMember: "1990", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Faroe_Islands_Football_Association_logo.svg/200px-Faroe_Islands_Football_Association_logo.svg.png", path: "app-universal-simple.html?club=Îles+Féroé&logo=🇫🇴&sport=Football+Federation&league=UEFA" },
    
    // EUROPE DU SUD
    { name: "Espagne", code: "ESP", flag: "🇪🇸", region: "Europe du Sud", president: "Pedro Rocha", founded: "1909", fifaMember: "1913", uefaMember: "1954", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/Royal_Spanish_Football_Federation_logo.svg/200px-Royal_Spanish_Football_Federation_logo.svg.png", path: "app-universal-simple.html?club=Espagne&logo=🇪🇸&sport=Football+Federation&league=UEFA" },
    { name: "Italie", code: "ITA", flag: "🇮🇹", region: "Europe du Sud", president: "Gabriele Gravina", founded: "1898", fifaMember: "1905", uefaMember: "1954", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/FIGC_Logo.svg/200px-FIGC_Logo.svg.png", path: "app-universal-simple.html?club=Italie&logo=🇮🇹&sport=Football+Federation&league=UEFA" },
    { name: "Portugal", code: "POR", flag: "🇵🇹", region: "Europe du Sud", president: "Fernando Gomes", founded: "1914", fifaMember: "1923", uefaMember: "1954", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Portuguese_Football_Federation_logo.svg/200px-Portuguese_Football_Federation_logo.svg.png", path: "app-universal-simple.html?club=Portugal&logo=🇵🇹&sport=Football+Federation&league=UEFA" },
    { name: "Grèce", code: "GRE", flag: "🇬🇷", region: "Europe du Sud", president: "Panagiotis Baltakos", founded: "1926", fifaMember: "1927", uefaMember: "1954", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Hellenic_Football_Federation_logo.svg/200px-Hellenic_Football_Federation_logo.svg.png", path: "app-universal-simple.html?club=Grèce&logo=🇬🇷&sport=Football+Federation&league=UEFA" },
    { name: "Turquie", code: "TUR", flag: "🇹🇷", region: "Europe du Sud", president: "İbrahim Hacıosmanoğlu", founded: "1923", fifaMember: "1923", uefaMember: "1962", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Turkish_Football_Federation_logo.svg/200px-Turkish_Football_Federation_logo.svg.png", path: "app-universal-simple.html?club=Turquie&logo=🇹🇷&sport=Football+Federation&league=UEFA" },
    { name: "Chypre", code: "CYP", flag: "🇨🇾", region: "Europe du Sud", president: "Giorgos Koumas", founded: "1934", fifaMember: "1948", uefaMember: "1962", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Cyprus_Football_Association_logo.svg/200px-Cyprus_Football_Association_logo.svg.png", path: "app-universal-simple.html?club=Chypre&logo=🇨🇾&sport=Football+Federation&league=UEFA" },
    { name: "Malte", code: "MLT", flag: "🇲🇹", region: "Europe du Sud", president: "Bjorn Vassallo", founded: "1900", fifaMember: "1959", uefaMember: "1960", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Malta_Football_Association_logo.svg/200px-Malta_Football_Association_logo.svg.png", path: "app-universal-simple.html?club=Malte&logo=🇲🇹&sport=Football+Federation&league=UEFA" },
    { name: "Andorre", code: "AND", flag: "🇦🇩", region: "Europe du Sud", president: "Joan Clotet", founded: "1994", fifaMember: "1996", uefaMember: "1996", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Andorran_Football_Federation_logo.svg/200px-Andorran_Football_Federation_logo.svg.png", path: "app-universal-simple.html?club=Andorre&logo=🇦🇩&sport=Football+Federation&league=UEFA" },
    { name: "Saint-Marin", code: "SMR", flag: "🇸🇲", region: "Europe du Sud", president: "Marco Tura", founded: "1931", fifaMember: "1988", uefaMember: "1988", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/San_Marino_Football_Federation_logo.svg/200px-San_Marino_Football_Federation_logo.svg.png", path: "app-universal-simple.html?club=Saint-Marin&logo=🇸🇲&sport=Football+Federation&league=UEFA" },
    { name: "Gibraltar", code: "GIB", flag: "🇬🇮", region: "Europe du Sud", president: "Michael Llamas", founded: "1895", fifaMember: "2016", uefaMember: "2013", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Gibraltar_Football_Association_logo.svg/200px-Gibraltar_Football_Association_logo.svg.png", path: "app-universal-simple.html?club=Gibraltar&logo=🇬🇮&sport=Football+Federation&league=UEFA" },
    { name: "Israël", code: "ISR", flag: "🇮🇱", region: "Europe du Sud", president: "Moshe Zuares", founded: "1928", fifaMember: "1929", uefaMember: "1994", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Israel_Football_Association_logo.svg/200px-Israel_Football_Association_logo.svg.png", path: "app-universal-simple.html?club=Israël&logo=🇮🇱&sport=Football+Federation&league=UEFA" },
    
    // EUROPE DE L'EST
    { name: "Pologne", code: "POL", flag: "🇵🇱", region: "Europe de l'Est", president: "Cezary Kulesza", founded: "1919", fifaMember: "1923", uefaMember: "1955", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c0/Polish_Football_Association_logo.svg/200px-Polish_Football_Association_logo.svg.png", path: "app-universal-simple.html?club=Pologne&logo=🇵🇱&sport=Football+Federation&league=UEFA" },
    { name: "République tchèque", code: "CZE", flag: "🇨🇿", region: "Europe de l'Est", president: "Petr Fousek", founded: "1993", fifaMember: "1994", uefaMember: "1993", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/Football_Association_of_the_Czech_Republic_logo.svg/200px-Football_Association_of_the_Czech_Republic_logo.svg.png", path: "app-universal-simple.html?club=République+tchèque&logo=🇨🇿&sport=Football+Federation&league=UEFA" },
    { name: "Slovaquie", code: "SVK", flag: "🇸🇰", region: "Europe de l'Est", president: "Ján Kováčik", founded: "1993", fifaMember: "1994", uefaMember: "1993", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/Slovak_Football_Association_logo.svg/200px-Slovak_Football_Association_logo.svg.png", path: "app-universal-simple.html?club=Slovaquie&logo=🇸🇰&sport=Football+Federation&league=UEFA" },
    { name: "Hongrie", code: "HUN", flag: "🇭🇺", region: "Europe de l'Est", president: "Sándor Csányi", founded: "1901", fifaMember: "1907", uefaMember: "1954", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Hungarian_Football_Federation_logo.svg/200px-Hungarian_Football_Federation_logo.svg.png", path: "app-universal-simple.html?club=Hongrie&logo=🇭🇺&sport=Football+Federation&league=UEFA" },
    { name: "Roumanie", code: "ROU", flag: "🇷🇴", region: "Europe de l'Est", president: "Răzvan Burleanu", founded: "1909", fifaMember: "1923", uefaMember: "1954", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/Romanian_Football_Federation_logo.svg/200px-Romanian_Football_Federation_logo.svg.png", path: "app-universal-simple.html?club=Roumanie&logo=🇷🇴&sport=Football+Federation&league=UEFA" },
    { name: "Bulgarie", code: "BUL", flag: "🇧🇬", region: "Europe de l'Est", president: "Mihail Kasabov", founded: "1923", fifaMember: "1924", uefaMember: "1954", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Bulgarian_Football_Union_logo.svg/200px-Bulgarian_Football_Union_logo.svg.png", path: "app-universal-simple.html?club=Bulgarie&logo=🇧🇬&sport=Football+Federation&league=UEFA" },
    { name: "Ukraine", code: "UKR", flag: "🇺🇦", region: "Europe de l'Est", president: "Andriy Pavelko", founded: "1991", fifaMember: "1992", uefaMember: "1992", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Ukrainian_Association_of_Football_logo.svg/200px-Ukrainian_Association_of_Football_logo.svg.png", path: "app-universal-simple.html?club=Ukraine&logo=🇺🇦&sport=Football+Federation&league=UEFA" },
    { name: "Biélorussie", code: "BLR", flag: "🇧🇾", region: "Europe de l'Est", president: "Gennadiy Nevyglas", founded: "1989", fifaMember: "1992", uefaMember: "1993", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Football_Federation_of_Belarus_logo.svg/200px-Football_Federation_of_Belarus_logo.svg.png", path: "app-universal-simple.html?club=Biélorussie&logo=🇧🇾&sport=Football+Federation&league=UEFA" },
    { name: "Moldavie", code: "MDA", flag: "🇲🇩", region: "Europe de l'Est", president: "Leonid Oleiniciuc", founded: "1990", fifaMember: "1994", uefaMember: "1993", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Moldovan_Football_Federation_logo.svg/200px-Moldovan_Football_Federation_logo.svg.png", path: "app-universal-simple.html?club=Moldavie&logo=🇲🇩&sport=Football+Federation&league=UEFA" },
    { name: "Russie", code: "RUS", flag: "🇷🇺", region: "Europe de l'Est", president: "Aleksandr Dyukov", founded: "1912", fifaMember: "1912", uefaMember: "1954", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Russian_Football_Union_logo.svg/200px-Russian_Football_Union_logo.svg.png", path: "app-universal-simple.html?club=Russie&logo=🇷🇺&sport=Football+Federation&league=UEFA" },
    
    // EUROPE DU SUD-EST (BALKANS)
    { name: "Croatie", code: "CRO", flag: "🇭🇷", region: "Balkans", president: "Marijan Kustić", founded: "1912", fifaMember: "1992", uefaMember: "1993", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Croatian_Football_Federation_logo.svg/200px-Croatian_Football_Federation_logo.svg.png", path: "app-universal-simple.html?club=Croatie&logo=🇭🇷&sport=Football+Federation&league=UEFA" },
    { name: "Serbie", code: "SRB", flag: "🇷🇸", region: "Balkans", president: "Dragan Džajić", founded: "1919", fifaMember: "1921", uefaMember: "1954", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Football_Association_of_Serbia_logo.svg/200px-Football_Association_of_Serbia_logo.svg.png", path: "app-universal-simple.html?club=Serbie&logo=🇷🇸&sport=Football+Federation&league=UEFA" },
    { name: "Bosnie-Herzégovine", code: "BIH", flag: "🇧🇦", region: "Balkans", president: "Vico Zeljković", founded: "1992", fifaMember: "1996", uefaMember: "1998", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Football_Association_of_Bosnia_and_Herzegovina_logo.svg/200px-Football_Association_of_Bosnia_and_Herzegovina_logo.svg.png", path: "app-universal-simple.html?club=Bosnie-Herzégovine&logo=🇧🇦&sport=Football+Federation&league=UEFA" },
    { name: "Monténégro", code: "MNE", flag: "🇲🇪", region: "Balkans", president: "Dejan Savićević", founded: "1931", fifaMember: "2007", uefaMember: "2007", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Football_Association_of_Montenegro_logo.svg/200px-Football_Association_of_Montenegro_logo.svg.png", path: "app-universal-simple.html?club=Monténégro&logo=🇲🇪&sport=Football+Federation&league=UEFA" },
    { name: "Macédoine du Nord", code: "MKD", flag: "🇲🇰", region: "Balkans", president: "Muamed Sejdini", founded: "1908", fifaMember: "1994", uefaMember: "1994", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Football_Federation_of_North_Macedonia_logo.svg/200px-Football_Federation_of_North_Macedonia_logo.svg.png", path: "app-universal-simple.html?club=Macédoine+du+Nord&logo=🇲🇰&sport=Football+Federation&league=UEFA" },
    { name: "Albanie", code: "ALB", flag: "🇦🇱", region: "Balkans", president: "Armand Duka", founded: "1930", fifaMember: "1932", uefaMember: "1954", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Albanian_Football_Association_logo.svg/200px-Albanian_Football_Association_logo.svg.png", path: "app-universal-simple.html?club=Albanie&logo=🇦🇱&sport=Football+Federation&league=UEFA" },
    { name: "Kosovo", code: "KOS", flag: "🇽🇰", region: "Balkans", president: "Agim Ademi", founded: "1946", fifaMember: "2016", uefaMember: "2016", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Football_Federation_of_Kosovo_logo.svg/200px-Football_Federation_of_Kosovo_logo.svg.png", path: "app-universal-simple.html?club=Kosovo&logo=🇽🇰&sport=Football+Federation&league=UEFA" },
    { name: "Slovénie", code: "SVN", flag: "🇸🇮", region: "Balkans", president: "Radenko Mijatović", founded: "1920", fifaMember: "1992", uefaMember: "1992", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Football_Association_of_Slovenia_logo.svg/200px-Football_Association_of_Slovenia_logo.svg.png", path: "app-universal-simple.html?club=Slovénie&logo=🇸🇮&sport=Football+Federation&league=UEFA" },
    
    // CAUCASE ET ASIE CENTRALE
    { name: "Géorgie", code: "GEO", flag: "🇬🇪", region: "Caucase", president: "Levan Kobiashvili", founded: "1990", fifaMember: "1992", uefaMember: "1992", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Georgian_Football_Federation_logo.svg/200px-Georgian_Football_Federation_logo.svg.png", path: "app-universal-simple.html?club=Géorgie&logo=🇬🇪&sport=Football+Federation&league=UEFA" },
    { name: "Arménie", code: "ARM", flag: "🇦🇲", region: "Caucase", president: "Armen Melikbekyan", founded: "1992", fifaMember: "1992", uefaMember: "1992", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Football_Federation_of_Armenia_logo.svg/200px-Football_Federation_of_Armenia_logo.svg.png", path: "app-universal-simple.html?club=Arménie&logo=🇦🇲&sport=Football+Federation&league=UEFA" },
    { name: "Azerbaïdjan", code: "AZE", flag: "🇦🇿", region: "Caucase", president: "Rovnag Abdullayev", founded: "1992", fifaMember: "1994", uefaMember: "1994", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Association_of_Football_Federations_of_Azerbaijan_logo.svg/200px-Association_of_Football_Federations_of_Azerbaijan_logo.svg.png", path: "app-universal-simple.html?club=Azerbaïdjan&logo=🇦🇿&sport=Football+Federation&league=UEFA" },
    { name: "Kazakhstan", code: "KAZ", flag: "🇰🇿", region: "Asie Centrale", president: "Adlet Barmenkulov", founded: "1914", fifaMember: "1994", uefaMember: "2002", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Kazakhstan_Football_Federation_logo.svg/200px-Kazakhstan_Football_Federation_logo.svg.png", path: "app-universal-simple.html?club=Kazakhstan&logo=🇰🇿&sport=Football+Federation&league=UEFA" },
    
    // PAYS BALTES
    { name: "Estonie", code: "EST", flag: "🇪🇪", region: "Pays Baltes", president: "Aivar Pohlak", founded: "1921", fifaMember: "1923", uefaMember: "1992", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Estonian_Football_Association_logo.svg/200px-Estonian_Football_Association_logo.svg.png", path: "app-universal-simple.html?club=Estonie&logo=🇪🇪&sport=Football+Federation&league=UEFA" },
    { name: "Lettonie", code: "LVA", flag: "🇱🇻", region: "Pays Baltes", president: "Vadims Ļašenko", founded: "1921", fifaMember: "1922", uefaMember: "1992", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Latvian_Football_Federation_logo.svg/200px-Latvian_Football_Federation_logo.svg.png", path: "app-universal-simple.html?club=Lettonie&logo=🇱🇻&sport=Football+Federation&league=UEFA" },
    { name: "Lituanie", code: "LTU", flag: "🇱🇹", region: "Pays Baltes", president: "Tomas Danilevičius", founded: "1922", fifaMember: "1923", uefaMember: "1992", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Lithuanian_Football_Federation_logo.svg/200px-Lithuanian_Football_Federation_logo.svg.png", path: "app-universal-simple.html?club=Lituanie&logo=🇱🇹&sport=Football+Federation&league=UEFA" }
];

console.log('✅ Fédérations UEFA chargées:', uefaMembersWithLogos.length);
