/* ═══════════════════════════════════════════════════════════════
   CLUB THEMES - Dynamic Per-Club Design System
   Each club defines its complete visual identity + metadata
   ═══════════════════════════════════════════════════════════════ */

export const CLUB_THEMES = {
  'psg': {
    id: 'psg',
    name: 'Paris Saint-Germain',
    shortName: 'PSG',
    category: 'French Football Clubs',
    tagline: 'Ici c\'est Paris',
    crestEmoji: '🗼',
    crestUrl: '/images/clubs/PARIS-SAINT-GERMAN.png',
    primaryColor: '#004170',
    secondaryColor: '#DA291C',
    accentColor: '#D4AF37',
    darkColor: '#050815',
    bgGradient: 'linear-gradient(135deg, #050815 0%, #002040 40%, #1a0010 70%, #050815 100%)',
    cardGradient: 'linear-gradient(145deg, #004170 0%, #001030 100%)',
    heroGradient: 'linear-gradient(180deg, #002050 0%, #0a0f20 40%, #050815 100%)',
    glowColor: 'rgba(218, 41, 28, 0.4)',
    glowColorStrong: 'rgba(218, 41, 28, 0.6)',
    textOnBg: '#e6f0ff',
    cardBgImage: '/images/stadium-bg.png',
    founded: 1970,
    stadium: 'Parc des Princes',
    manager: 'Luis Enrique',
    league: 'Ligue 1',
    country: '🇫🇷 France',
    countryCode: 'FR',
    trophies: { league: { count: 12, label: 'Ligue 1', icon: '🥇' } },
    description: 'Paris Saint-Germain, the crown jewel of French football.',
    featured: true,
    squad: [{ name: 'Ousmane Dembélé', position: 'Forward', number: 10, emoji: '⚡' }],
  },

  'as-nancy-lorraine': {
    id: 'as-nancy-lorraine',
    name: 'AS Nancy Lorraine',
    shortName: 'ASNL',
    category: 'French Football Clubs',
    tagline: 'Qui s\'y frotte s\'y pique',
    crestEmoji: '🌹',
    crestUrl: '/images/clubs/AS-NANCY-LORRAINE.png',
    primaryColor: '#E30613',
    secondaryColor: '#FFFFFF',
    accentColor: '#E30613',
    darkColor: '#1a0505',
    bgGradient: 'linear-gradient(135deg, #1a0505 0%, #400000 40%, #E30613 70%, #1a0505 100%)',
    cardGradient: 'linear-gradient(145deg, #E30613 0%, #200000 100%)',
    heroGradient: 'linear-gradient(180deg, #600000 0%, #200000 40%, #1a0505 100%)',
    glowColor: 'rgba(227, 6, 19, 0.4)',
    glowColorStrong: 'rgba(227, 6, 19, 0.6)',
    textOnBg: '#fff0f0',
    cardBgImage: '/images/stadium-bg.png',
    founded: 1967,
    stadium: 'Stade Marcel-Picot',
    manager: 'Pablo Correa',
    league: 'National 1',
    country: '🇫🇷 France',
    countryCode: 'FR',
    trophies: { cup: { count: 1, label: 'Coupe de France', icon: '🏅' } },
    description: 'AS Nancy Lorraine is a club with a proud history.',
    squad: [{ name: 'Maxence Carlier', position: 'Defender', number: 5, emoji: '🛡️' }],
  },

  'clermont-foot-63': {
    id: 'clermont-foot-63',
    name: 'Clermont Foot 63',
    shortName: 'CF63',
    category: 'French Football Clubs',
    tagline: 'Plus haut, plus fort',
    crestEmoji: '🌋',
    crestUrl: '/images/clubs/CLERMONT-FOOT-63.png',
    primaryColor: '#820E2E',
    secondaryColor: '#1F244F',
    accentColor: '#FFFFFF',
    darkColor: '#0a0508',
    bgGradient: 'linear-gradient(135deg, #0a0508 0%, #300810 40%, #1F244F 70%, #0a0508 100%)',
    cardGradient: 'linear-gradient(145deg, #820E2E 0%, #100508 100%)',
    heroGradient: 'linear-gradient(180deg, #400a15 0%, #150510 40%, #0a0508 100%)',
    glowColor: 'rgba(130, 14, 46, 0.4)',
    glowColorStrong: 'rgba(130, 14, 46, 0.6)',
    textOnBg: '#ffeef0',
    cardBgImage: '/images/stadium-bg.png',
    founded: 1911,
    stadium: 'Stade Gabriel-Montpied',
    manager: 'Sébastien Mazeyrat',
    league: 'Ligue 2',
    country: '🇫🇷 France',
    countryCode: 'FR',
    trophies: {},
    description: 'Based in the volcanic region of Auvergne.',
    squad: [{ name: 'Johan Gastien', position: 'Midfielder', number: 25, emoji: '🎯' }],
  },

  'red-star-fc': {
    id: 'red-star-fc',
    name: 'Red Star FC',
    shortName: 'RSFC',
    category: 'French Football Clubs',
    tagline: 'Notre Cœur est Vert',
    crestEmoji: '⭐',
    crestUrl: '/images/clubs/RED-STAR-FC.png',
    primaryColor: '#00754A',
    secondaryColor: '#FFFFFF',
    accentColor: '#E30613',
    darkColor: '#051a0d',
    bgGradient: 'linear-gradient(135deg, #051a0d 0%, #004d31 40%, #00754A 70%, #051a0d 100%)',
    cardGradient: 'linear-gradient(145deg, #00754A 0%, #002e1d 100%)',
    heroGradient: 'linear-gradient(180deg, #004d31 0%, #0a1f14 40%, #051a0d 100%)',
    glowColor: 'rgba(0, 117, 74, 0.4)',
    glowColorStrong: 'rgba(0, 117, 74, 0.6)',
    textOnBg: '#eafff5',
    cardBgImage: '/images/stadium-bg.png',
    founded: 1897,
    stadium: 'Stade Bauer',
    manager: 'Grégory Poirier',
    league: 'Ligue 2',
    country: '🇫🇷 France',
    countryCode: 'FR',
    trophies: { cup: { count: 5, label: 'Coupe de France', icon: '🏅' } },
    description: 'The historic soul of Parisian football.',
    squad: [{ name: 'Merwan Ifnaoui', position: 'Midfielder', number: 10, emoji: '✨' }],
  },

  'stade-lavallois': {
    id: 'stade-lavallois',
    name: 'Stade Lavallois',
    shortName: 'SL',
    category: 'French Football Clubs',
    tagline: 'Fiers d\'être Tangos',
    crestEmoji: '🟠',
    crestUrl: '/images/clubs/STADE-LAVALLOIS.png',
    primaryColor: '#FF6600',
    secondaryColor: '#000000',
    accentColor: '#FFFFFF',
    darkColor: '#1a0d05',
    bgGradient: 'linear-gradient(135deg, #1a0d05 0%, #401a00 40%, #FF6600 70%, #1a0d05 100%)',
    cardGradient: 'linear-gradient(145deg, #FF6600 0%, #200d00 100%)',
    heroGradient: 'linear-gradient(180deg, #602800 0%, #200d00 40%, #1a0d05 100%)',
    glowColor: 'rgba(255, 102, 0, 0.4)',
    glowColorStrong: 'rgba(255, 102, 0, 0.6)',
    textOnBg: '#fff5f0',
    cardBgImage: '/images/stadium-bg.png',
    founded: 1902,
    stadium: 'Stade Francis Le Basser',
    manager: 'Olivier Frapolli',
    league: 'Ligue 2',
    country: '🇫🇷 France',
    countryCode: 'FR',
    trophies: {},
    description: 'The Tangos of Laval.',
    squad: [{ name: 'Malik Sellouki', position: 'Midfielder', number: 10, emoji: '✨' }],
  },

  'paris-fc': {
    id: 'paris-fc',
    name: 'Paris FC',
    shortName: 'PFC',
    category: 'French Football Clubs',
    tagline: 'Paris est notre terrain',
    crestEmoji: '🗼',
    crestUrl: '/images/clubs/PARIS-FC.png',
    primaryColor: '#003366',
    secondaryColor: '#FFFFFF',
    accentColor: '#00AEEF',
    darkColor: '#050a18',
    bgGradient: 'linear-gradient(135deg, #050a18 0%, #001a33 40%, #003366 70%, #050a18 100%)',
    cardGradient: 'linear-gradient(145deg, #003366 0%, #001020 100%)',
    heroGradient: 'linear-gradient(180deg, #002040 0%, #0a0f20 40%, #050a18 100%)',
    glowColor: 'rgba(0, 51, 102, 0.4)',
    glowColorStrong: 'rgba(0, 51, 102, 0.6)',
    textOnBg: '#e6f2ff',
    cardBgImage: '/images/stadium-bg.png',
    founded: 1969,
    stadium: 'Stade Jean-Bouin',
    manager: 'Stéphane Gilli',
    league: 'Ligue 2',
    country: '🇫🇷 France',
    countryCode: 'FR',
    trophies: {},
    description: 'The other club of Paris.',
    squad: [{ name: 'Ilan Kebbal', position: 'Midfielder', number: 10, emoji: '✨' }],
  },

  'sc-bastia': {
    id: 'sc-bastia',
    name: 'SC Bastia',
    shortName: 'SCB',
    category: 'French Football Clubs',
    tagline: 'Fino Alla Morte',
    crestEmoji: '🛡️',
    crestUrl: '/images/clubs/SC-BASTIA.png',
    primaryColor: '#004F9F',
    secondaryColor: '#FFFFFF',
    accentColor: '#004F9F',
    darkColor: '#050a1a',
    bgGradient: 'linear-gradient(135deg, #050a1a 0%, #002d5c 40%, #004F9F 70%, #050a1a 100%)',
    cardGradient: 'linear-gradient(145deg, #004F9F 0%, #002040 100%)',
    heroGradient: 'linear-gradient(180deg, #003d7a 0%, #0a0f1a 40%, #050a1a 100%)',
    glowColor: 'rgba(0, 79, 159, 0.4)',
    glowColorStrong: 'rgba(0, 79, 159, 0.6)',
    textOnBg: '#e6f0ff',
    cardBgImage: '/images/stadium-bg.png',
    founded: 1905,
    stadium: 'Stade Armand-Cesari',
    manager: 'Benoît Tavenot',
    league: 'Ligue 2',
    country: '🇫🇷 France',
    countryCode: 'FR',
    trophies: { cup: { count: 1, label: 'Coupe de France', icon: '🏅' } },
    description: 'The pride of Corsica.',
    squad: [{ name: 'Christophe Vincent', position: 'Midfielder', number: 10, emoji: '🛡️' }],
  },

  'olympique-de-marseille': {
    id: 'olympique-de-marseille',
    name: 'Olympique de Marseille',
    shortName: 'OM',
    category: 'French Football Clubs',
    tagline: 'Droit au But',
    crestEmoji: '🔵',
    crestUrl: '/images/clubs/OLYMPIQUE-DE-MARSEILLE.png',
    primaryColor: '#00ABF0',
    secondaryColor: '#FFFFFF',
    accentColor: '#D4AF37',
    darkColor: '#051020',
    bgGradient: 'linear-gradient(135deg, #051020 0%, #003050 40%, #00ABF0 70%, #051020 100%)',
    cardGradient: 'linear-gradient(145deg, #00ABF0 0%, #001a30 100%)',
    heroGradient: 'linear-gradient(180deg, #003a60 0%, #0a0f20 40%, #051020 100%)',
    glowColor: 'rgba(0, 171, 240, 0.4)',
    glowColorStrong: 'rgba(0, 171, 240, 0.6)',
    textOnBg: '#e6f7ff',
    cardBgImage: '/images/stadium-bg.png',
    founded: 1899,
    stadium: 'Orange Vélodrome',
    manager: 'Roberto De Zerbi',
    league: 'Ligue 1',
    country: '🇫🇷 France',
    countryCode: 'FR',
    trophies: { championsLeague: { count: 1, label: 'Champions League', icon: '🏆' } },
    description: 'The only French club to win the Champions League.',
    squad: [{ name: 'Mason Greenwood', position: 'Forward', number: 10, emoji: '⚡' }],
  },

  'fc-versailles': {
    id: 'fc-versailles',
    name: 'FC Versailles',
    shortName: 'FCV',
    category: 'French Football Clubs',
    tagline: 'L\'esprit Royal',
    crestEmoji: '👑',
    crestUrl: '/images/clubs/FC-VERSAILLES.png',
    primaryColor: '#002D62',
    secondaryColor: '#D4AF37',
    accentColor: '#D4AF37',
    darkColor: '#050a15',
    bgGradient: 'linear-gradient(135deg, #050a15 0%, #001a3d 40%, #002D62 70%, #050a15 100%)',
    cardGradient: 'linear-gradient(145deg, #002D62 0%, #001020 100%)',
    heroGradient: 'linear-gradient(180deg, #001a3d 0%, #0a0f1a 40%, #050a15 100%)',
    glowColor: 'rgba(212, 175, 55, 0.35)',
    glowColorStrong: 'rgba(212, 175, 55, 0.55)',
    textOnBg: '#fef9e7',
    cardBgImage: '/images/stadium-bg.png',
    founded: 1989,
    stadium: 'Stade Montbauron',
    manager: 'Jordan Gonzalez',
    league: 'National 1',
    country: '🇫🇷 France',
    countryCode: 'FR',
    trophies: {},
    description: 'Representing the city of Versailles.',
    squad: [{ name: 'Raphaël Calvet', position: 'Defender', number: 5, emoji: '🏰' }],
  },

  'le-havre-ac': {
    id: 'le-havre-ac',
    name: 'Le Havre AC',
    shortName: 'HAC',
    category: 'French Football Clubs',
    tagline: 'Le Ciel et la Marine',
    crestEmoji: '🌊',
    crestUrl: '/images/clubs/LE-HAVRE-AC.png',
    primaryColor: '#87CEEB',
    secondaryColor: '#001A3D',
    accentColor: '#FFFFFF',
    darkColor: '#050a1a',
    bgGradient: 'linear-gradient(135deg, #050a1a 0%, #002d5c 40%, #87CEEB 70%, #050a1a 100%)',
    cardGradient: 'linear-gradient(145deg, #87CEEB 0%, #001A3D 100%)',
    heroGradient: 'linear-gradient(180deg, #004d99 0%, #0a1426 40%, #050a1a 100%)',
    glowColor: 'rgba(135, 206, 235, 0.4)',
    glowColorStrong: 'rgba(135, 206, 235, 0.6)',
    textOnBg: '#f0fbff',
    cardBgImage: '/images/stadium-bg.png',
    founded: 1872,
    stadium: 'Stade Océane',
    manager: 'Didier Digard',
    league: 'Ligue 1',
    country: '🇫🇷 France',
    countryCode: 'FR',
    trophies: { cup: { count: 1, label: 'Coupe de France', icon: '🏅' } },
    description: 'The "Dean Club" of French football.',
    squad: [{ name: 'Abdoulaye Touré', position: 'Midfielder', number: 22, emoji: '🛡️' }],
  },

  'montpellier-hsc': {
    id: 'montpellier-hsc',
    name: 'Montpellier HSC',
    shortName: 'MHSC',
    category: 'French Football Clubs',
    tagline: 'Ici c\'est la Paillade',
    crestEmoji: '🔵',
    crestUrl: '/images/clubs/MONTPELLIER HSC.png',
    primaryColor: '#003366',
    secondaryColor: '#FF6600',
    accentColor: '#FFFFFF',
    darkColor: '#050a18',
    bgGradient: 'linear-gradient(135deg, #050a18 0%, #001a33 40%, #FF6600 70%, #050a18 100%)',
    cardGradient: 'linear-gradient(145deg, #003366 0%, #200d00 100%)',
    heroGradient: 'linear-gradient(180deg, #002040 0%, #150500 40%, #050a18 100%)',
    glowColor: 'rgba(255, 102, 0, 0.4)',
    glowColorStrong: 'rgba(255, 102, 0, 0.6)',
    textOnBg: '#fff5f0',
    cardBgImage: '/images/stadium-bg.png',
    founded: 1974,
    stadium: 'Stade de la Mosson',
    manager: 'Zoumana Camara',
    league: 'Ligue 1',
    country: '🇫🇷 France',
    countryCode: 'FR',
    trophies: { league: { count: 1, label: 'Ligue 1', icon: '🥇' } },
    description: 'Montpellier HSC won Ligue 1 in 2012.',
    squad: [{ name: 'Téji Savanier', position: 'Midfielder', number: 10, emoji: '🎯' }],
  },

  'sm-caen': {
    id: 'sm-caen',
    name: 'SM Caen',
    shortName: 'SMC',
    category: 'French Football Clubs',
    tagline: 'Normands et Conquérants',
    crestEmoji: '🛡️',
    crestUrl: '/images/clubs/SM CAEN.png',
    primaryColor: '#1F244F',
    secondaryColor: '#E30613',
    accentColor: '#FFFFFF',
    darkColor: '#0a0a1a',
    bgGradient: 'linear-gradient(135deg, #0a0a1a 0%, #000c26 40%, #E30613 70%, #0a0a1a 100%)',
    cardGradient: 'linear-gradient(145deg, #1F244F 0%, #200000 100%)',
    heroGradient: 'linear-gradient(180deg, #101430 0%, #100000 40%, #0a0a1a 100%)',
    glowColor: 'rgba(227, 6, 19, 0.4)',
    glowColorStrong: 'rgba(227, 6, 19, 0.6)',
    textOnBg: '#fff0f0',
    cardBgImage: '/images/stadium-bg.png',
    founded: 1913,
    stadium: 'Stade Michel d\'Ornano',
    manager: 'Nicolas Seube',
    league: 'Ligue 2',
    country: '🇫🇷 France',
    countryCode: 'FR',
    trophies: {},
    description: 'SM Caen, owned by the Mbappé family office.',
    squad: [{ name: 'Alexandre Mendy', position: 'Forward', number: 19, emoji: '🔥' }],
  },

  'bourges-fc': {
    id: 'bourges-fc',
    name: 'Bourges FC',
    shortName: 'BFC',
    category: 'French Football Clubs',
    tagline: 'L\'Ambition du Berry',
    crestEmoji: '🏰',
    crestUrl: '/images/clubs/BOURGES-FC.jpg',
    primaryColor: '#E30613',
    secondaryColor: '#FFD700',
    accentColor: '#FFFFFF',
    darkColor: '#1a0505',
    bgGradient: 'linear-gradient(135deg, #1a0505 0%, #400000 40%, #FFD700 70%, #1a0505 100%)',
    cardGradient: 'linear-gradient(145deg, #E30613 0%, #200000 100%)',
    heroGradient: 'linear-gradient(180deg, #600000 0%, #302000 40%, #1a0505 100%)',
    glowColor: 'rgba(255, 215, 0, 0.4)',
    glowColorStrong: 'rgba(255, 215, 0, 0.6)',
    textOnBg: '#fffef0',
    cardBgImage: '/images/stadium-bg.png',
    founded: 1966,
    stadium: 'Stade Jacques Rimbault',
    manager: 'Jordan Gonzalez',
    league: 'National 2',
    country: '🇫🇷 France',
    countryCode: 'FR',
    trophies: {},
    description: 'Owned by Sadio Mané.',
    squad: [{ name: 'Sadio Mané', position: 'Ambassador', number: 10, emoji: '🌟' }],
  },

  'cs-sedan-ardennes': {
    id: 'cs-sedan-ardennes',
    name: 'CS Sedan Ardennes',
    shortName: 'CSSA',
    category: 'French Football Clubs',
    tagline: 'Allez Sedan!',
    crestEmoji: '🐗',
    crestUrl: '/images/clubs/CS-SEDAN-ARDENNES.png',
    primaryColor: '#E30613',
    secondaryColor: '#008000',
    accentColor: '#FFFFFF',
    darkColor: '#1a0505',
    bgGradient: 'linear-gradient(135deg, #1a0505 0%, #400000 40%, #008000 70%, #1a0505 100%)',
    cardGradient: 'linear-gradient(145deg, #E30613 0%, #002000 100%)',
    heroGradient: 'linear-gradient(180deg, #600000 0%, #003000 40%, #1a0505 100%)',
    glowColor: 'rgba(0, 128, 0, 0.4)',
    glowColorStrong: 'rgba(0, 128, 0, 0.6)',
    textOnBg: '#f0fff0',
    cardBgImage: '/images/stadium-bg.png',
    founded: 1919,
    stadium: 'Stade Louis Dugauguez',
    manager: 'Elise Bussaglia',
    league: 'Regional 1',
    country: '🇫🇷 France',
    countryCode: 'FR',
    trophies: { cup: { count: 2, label: 'Coupe de France', icon: '🏅' } },
    description: 'The Wild Boars of Ardennes.',
    squad: [],
  },

  'as-saint-etienne': {
    id: 'as-saint-etienne',
    name: 'AS Saint-Étienne',
    shortName: 'ASSE',
    category: 'French Football Clubs',
    tagline: 'Allez les Verts',
    crestEmoji: '🟢',
    crestUrl: '/images/clubs/AS-SAINT-ETIIENNE.png',
    primaryColor: '#008F45',
    secondaryColor: '#FFFFFF',
    accentColor: '#D4AF37',
    darkColor: '#051a0d',
    bgGradient: 'linear-gradient(135deg, #051a0d 0%, #004d26 40%, #008F45 70%, #051a0d 100%)',
    cardGradient: 'linear-gradient(145deg, #008F45 0%, #002e17 100%)',
    heroGradient: 'linear-gradient(180deg, #004d26 0%, #0a1f14 40%, #051a0d 100%)',
    glowColor: 'rgba(0, 143, 69, 0.4)',
    glowColorStrong: 'rgba(0, 143, 69, 0.6)',
    textOnBg: '#eafff5',
    cardBgImage: '/images/stadium-bg.png',
    founded: 1919,
    stadium: 'Stade Geoffroy-Guichard',
    manager: 'Olivier Dall\'Oglio',
    league: 'Ligue 1',
    country: '🇫🇷 France',
    countryCode: 'FR',
    trophies: { league: { count: 10, label: 'Ligue 1', icon: '🥇' } },
    description: 'The "Greens" are one of France\'s most successful clubs.',
    squad: [{ name: 'Ibrahim Sissoko', position: 'Forward', number: 9, emoji: '🔥' }],
  },

  'wydad-ac': {
    id: 'wydad-ac',
    name: 'Wydad Athletic Club',
    shortName: 'WAC',
    category: 'Morocco / Arabic Football',
    tagline: 'Always Wydad',
    crestEmoji: '🔴',
    crestUrl: '/images/clubs/WYDAD-ATHLETIC-CLUB.png',
    primaryColor: '#E30613',
    secondaryColor: '#FFFFFF',
    accentColor: '#FFD700',
    darkColor: '#1a0505',
    bgGradient: 'linear-gradient(135deg, #1a0505 0%, #400000 40%, #E30613 70%, #1a0505 100%)',
    cardGradient: 'linear-gradient(145deg, #E30613 0%, #200000 100%)',
    heroGradient: 'linear-gradient(180deg, #600000 0%, #200000 40%, #1a0505 100%)',
    glowColor: 'rgba(227, 6, 19, 0.4)',
    glowColorStrong: 'rgba(227, 6, 19, 0.6)',
    textOnBg: '#fff0f0',
    cardBgImage: '/images/stadium-bg.png',
    founded: 1937,
    stadium: 'Stade Mohammed V',
    manager: 'Rulani Mokwena',
    league: 'Botola Pro',
    country: '🇲🇦 Morocco',
    countryCode: 'MA',
    trophies: { championsLeague: { count: 3, label: 'CAF Champions League', icon: '🏆' } },
    description: 'The Red Castle of Casablanca.',
    squad: [{ name: 'M\'Baye Niang', position: 'Forward', number: 11, emoji: '⚡' }],
  },

  'morocco-federation': {
    id: 'morocco-federation',
    name: 'Morocco Federation',
    shortName: 'FRMF',
    category: 'Morocco / Arabic Football',
    tagline: 'Lions de l\'Atlas',
    crestEmoji: '🇲🇦',
    crestUrl: '/images/clubs/MOROCCO-FEDERATION.png',
    primaryColor: '#E30613',
    secondaryColor: '#006233',
    accentColor: '#FFD700',
    darkColor: '#1a0505',
    bgGradient: 'linear-gradient(135deg, #1a0505 0%, #006233 40%, #E30613 70%, #1a0505 100%)',
    cardGradient: 'linear-gradient(145deg, #E30613 0%, #00301a 100%)',
    heroGradient: 'linear-gradient(180deg, #600000 0%, #004d26 40%, #1a0505 100%)',
    glowColor: 'rgba(0, 98, 51, 0.4)',
    glowColorStrong: 'rgba(0, 98, 51, 0.6)',
    textOnBg: '#f0fff5',
    cardBgImage: '/images/stadium-bg.png',
    founded: 1955,
    stadium: 'Stade Moulay Abdellah',
    manager: 'Walid Regragui',
    league: 'National Team',
    country: '🇲🇦 Morocco',
    countryCode: 'MA',
    trophies: { afcon: { count: 1, label: 'AFCON', icon: '🏆' } },
    description: 'The Royal Moroccan Football Federation.',
    squad: [{ name: 'Achraf Hakimi', position: 'Defender', number: 2, emoji: '⚡' }],
  },

  'montpellier-rugby': {
    id: 'montpellier-rugby',
    name: 'Montpellier Rugby',
    shortName: 'MHR',
    category: 'Rugby',
    tagline: 'Ensemble Pour Gagner',
    crestEmoji: '🏉',
    crestUrl: '/images/clubs/MONTPELLER-RUGBY.png',
    primaryColor: '#003366',
    secondaryColor: '#87CEEB',
    accentColor: '#FFFFFF',
    darkColor: '#050a18',
    bgGradient: 'linear-gradient(135deg, #050a18 0%, #001a33 40%, #87CEEB 70%, #050a18 100%)',
    cardGradient: 'linear-gradient(145deg, #003366 0%, #001020 100%)',
    heroGradient: 'linear-gradient(180deg, #002040 0%, #0a0f20 40%, #050a18 100%)',
    glowColor: 'rgba(135, 206, 235, 0.4)',
    glowColorStrong: 'rgba(135, 206, 235, 0.6)',
    textOnBg: '#e6f2ff',
    cardBgImage: '/images/stadium-bg.png',
    founded: 1986,
    stadium: 'GGL Stadium',
    manager: 'Joan Caudullo',
    league: 'Top 14',
    country: '🇫🇷 France',
    countryCode: 'FR',
    trophies: { league: { count: 1, label: 'Top 14', icon: '🥇' } },
    description: 'Elite club in the French Top 14 rugby league.',
    squad: [{ name: 'Stuart Hogg', position: 'Fullback', number: 15, emoji: '⚡' }],
  },

  'tanzania-federation': {
    id: 'tanzania-federation',
    name: 'Tanzania Federation',
    shortName: 'TFF',
    category: 'Tanzania (Swahili Region)',
    tagline: 'Taifa Stars',
    crestEmoji: '🇹🇿',
    crestUrl: '/images/clubs/TANZANIA-FEDERATION.png',
    primaryColor: '#00AEEF',
    secondaryColor: '#FFD700',
    accentColor: '#000000',
    darkColor: '#050a1a',
    bgGradient: 'linear-gradient(135deg, #050a1a 0%, #005c99 40%, #FFD700 70%, #050a1a 100%)',
    cardGradient: 'linear-gradient(145deg, #00AEEF 0%, #002040 100%)',
    heroGradient: 'linear-gradient(180deg, #004d99 0%, #302000 40%, #050a1a 100%)',
    glowColor: 'rgba(255, 215, 0, 0.4)',
    glowColorStrong: 'rgba(255, 215, 0, 0.6)',
    textOnBg: '#fffef0',
    cardBgImage: '/images/stadium-bg.png',
    founded: 1930,
    stadium: 'Benjamin Mkapa Stadium',
    manager: 'Hemed Morocco',
    league: 'National Team',
    country: '🇹🇿 Tanzania',
    countryCode: 'TZ',
    trophies: {},
    description: 'Leading the Taifa Stars.',
    squad: [{ name: 'Mbwana Samatta', position: 'Forward', number: 10, emoji: '🔥' }],
  },

  'senegal-federation': {
    id: 'senegal-federation',
    name: 'Senegal Federation',
    shortName: 'FSF',
    category: 'Senegal',
    tagline: 'Lions de la Téranga',
    crestEmoji: '🇸🇳',
    crestUrl: '/images/clubs/SENEGAL-FEDERATION.png',
    primaryColor: '#00853F',
    secondaryColor: '#FDEF42',
    accentColor: '#E31B23',
    darkColor: '#051a0d',
    bgGradient: 'linear-gradient(135deg, #051a0d 0%, #004d26 40%, #E31B23 70%, #051a0d 100%)',
    cardGradient: 'linear-gradient(145deg, #00853F 0%, #002e17 100%)',
    heroGradient: 'linear-gradient(180deg, #004d26 0%, #300000 40%, #051a0d 100%)',
    glowColor: 'rgba(227, 27, 35, 0.4)',
    glowColorStrong: 'rgba(227, 27, 35, 0.6)',
    textOnBg: '#fff0f0',
    cardBgImage: '/images/stadium-bg.png',
    founded: 1960,
    stadium: 'Stade Me Abdoulaye Wade',
    manager: 'Aliou Cissé',
    league: 'National Team',
    country: '🇸🇳 Senegal',
    countryCode: 'SN',
    trophies: { afcon: { count: 1, label: 'AFCON', icon: '🏆' } },
    description: 'Home of the reigning African Champions.',
    squad: [{ name: 'Sadio Mané', position: 'Forward', number: 10, emoji: '⚡' }],
  },
};

// Helper to get theme by club ID
export function getClubTheme(clubId) {
  return CLUB_THEMES[clubId] || null;
}

// Get all clubs as an array
export function getAllClubs() {
  return Object.values(CLUB_THEMES);
}

// Get featured club
export function getFeaturedClub() {
  return Object.values(CLUB_THEMES).find(c => c.featured) || Object.values(CLUB_THEMES)[0];
}

// Mock products tied to a club
export function getClubProducts(clubId) {
  const theme = getClubTheme(clubId);
  if (!theme) return [];

  const baseProducts = [
    { id: `${clubId}-1`, name: `Authentic OM Home Jersey 25/26`, category: 'Jersey', price: 127.50, currency: 'PCC', image: '/images/products/Home_jersey.webp', emoji: '👕' },
    { id: `${clubId}-2`, name: `OM Away Jersey 25/26`, category: 'Jersey', price: 156.00, currency: 'PCC', image: '/images/products/AWAY_JERSEY.webp', emoji: '👕' },
    { id: `${clubId}-3`, name: `OM Navy Blue Travel Jacket`, category: 'Jacket', price: 63.00, currency: 'PCC', image: '/images/products/JACKET.webp', emoji: '🧥' },
    { id: `${clubId}-4`, name: `Go OM scarf`, category: 'Accessory', price: 12.50, currency: 'PCC', image: '/images/products/scarf.webp', emoji: '🧣' },
    { id: `${clubId}-5`, name: `Casquette OM King Bleu/Blanche`, category: 'Accessory', price: 25.00, currency: 'PCC', image: '/images/products/cap.webp', emoji: '🧢' },
    { id: `${clubId}-6`, name: `OM Bracelet, Black Leather, Small Model`, category: 'Accessory', price: 49.50, currency: 'PCC', image: '/images/products/bracelet.webp', emoji: '🎁' },
  ];

  return baseProducts;
}

export const STADIUM_BG = '/images/stadium-bg.png';

export function injectClubTheme(element, clubId) {
  const theme = getClubTheme(clubId);
  if (!theme || !element) return;

  element.style.setProperty('--club-primary', theme.primaryColor);
  element.style.setProperty('--club-secondary', theme.secondaryColor);
  element.style.setProperty('--club-accent', theme.accentColor);
  element.style.setProperty('--club-dark', theme.darkColor);
  element.style.setProperty('--club-bg-gradient', theme.bgGradient);
  element.style.setProperty('--club-card-gradient', theme.cardGradient);
  element.style.setProperty('--club-hero-gradient', theme.heroGradient);
  element.style.setProperty('--club-glow', theme.glowColor);
  element.style.setProperty('--club-glow-strong', theme.glowColorStrong);
  element.style.setProperty('--club-text', theme.textOnBg);
}
